### ISSUE TITLE
Use of pyproject.toml and proper package manager

### ISSUE THREAD

**Issue by Jocelyn-Gas** [mkhorasani/Streamlit-Authenticator#105]
Hello there! 

First of all, thanks for the amazing package! 🔥 👏🏼 

I've been meaning to open a Pull Request to implement configurable languages for the forms. 

After cloning the repo, I was a bit surprised it didn't use any pyproject.toml. Maybe it's just that I'm not use to such setup, but I think it would help for users wanting to contribute to have a project manager such as Poetry or PDM. 

Are you open to me opening a PR to help set things up in this way before opening a second one for other features?

Thanks in advance!

**Comment by mkhorasani** [comment]
Hey @Jocelyn-Gas, you're most welcome. And yes please, go ahead! I look forward to seeing what you can contribute to our package. Cheers.
