### ISSUE TITLE
authenticator.login changed?

### ISSUE THREAD

**Issue by xu2xulim** [mkhorasani/Streamlit-Authenticator#107]
My code had been work for some time  but now I am getting.
File "/usr/local/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
File "/app/streamlit_app.py", line 70, in <module>
    name, authentication_status, username = authenticator.login('Login', 'sidebar')
File "/usr/local/lib/python3.9/site-packages/streamlit_authenticator/authenticate.py", line 240, in login
    raise ValueError("Location must be one of 'main' or 'sidebar'")

Now I have to change it to 
name, authentication_status, username = authenticator.login('sidebar')
For it to work. Was the change made recently?

**Comment by mkhorasani** [comment]
Hi @xu2xulim, please follow the readme file [here](https://github.com/mkhorasani/Streamlit-Authenticator?tab=readme-ov-file#parameters-1). In the latest release (v0.2.4), the **form_name** parameter has been removed from the widget and instead has been replaced with a **fields** parameter that enables you to customize any or all of the text fields in the form.
