### ISSUE TITLE
Adding id field to credentials breaks authentication on page reload

### ISSUE THREAD

**Issue by eytan-ohana** [mkhorasani/Streamlit-Authenticator#108]
Hi @mkhorasani,

I just wanted to start off with this is an excellent extension to streamlit!

In my use case, the users credentials (email and hashed password) are stored in a mongo database which is reloaded every time the user refreshes the page.

It looks like in the new release, [v0.2.4](https://github.com/mkhorasani/Streamlit-Authenticator/releases/tag/v0.2.4), with the addition of the id key in the credentials, 
https://github.com/mkhorasani/Streamlit-Authenticator/blob/a498615e0b7c8705268395f3e489e87f673a66c1/streamlit_authenticator/authenticate.py#L51

whenever the user reloads the page the id key is reset (because the session state is cleared) meaning now when the authenticator tries to search for the user based on the cookie/token here

https://github.com/mkhorasani/Streamlit-Authenticator/blob/a498615e0b7c8705268395f3e489e87f673a66c1/streamlit_authenticator/authenticate.py#L127

then it never actually finds the user because id has already been changed.

I hope that provides enough context :)

**Comment by mkhorasani** [comment]
Hi @eytan-ohana, thank you for reaching out. The ID field is not saved in the session state, it is actually saved in the config file just like the name, email, and hashed password. Please make sure you are saving new fields to your remote database to ensure that it does not break down.

**Comment by mkhorasani** [comment]
And just for your information the ID is not related to Streamlit's session_id, it is a randomly generated the first time the field is populated.

**Comment by eytan-ohana** [comment]
HI @mkhorasani 
thanks for the quick response. What I mean to say is every time the session state is refreshed the id is regenerated so without saving the id to my external db thats where the reauthentication fails.

Looks like youre right ill go ahead and save the generated ids to the db too. It looks like the only way i can do that is through accessing the authenticator objects `credentials` attribute after the object is created, which doesn't seem too clean to me but should still work fine just the same.

thanks for your support!

**Comment by mkhorasani** [comment]
Hi @eytan-ohana, I have decided to axe Streamlit-Authenticator v0.2.5 and replace it with [v0.3.0](https://github.com/mkhorasani/Streamlit-Authenticator/releases/tag/v0.3.0). The 'ID' field is now removed and you will no longer need to worry about it. Many thanks.

**Comment by eytan-ohana** [comment]
Thats awesome news @mkhorasani thanks for letting me know!

Can I ask what prompted that decision?

**Comment by mkhorasani** [comment]
I believe it will not provide any added value and it led to an influx of issues being raised by developers who were updating to the latest version without updating their code.

**Comment by eytan-ohana** [comment]
Makes sense Thank you!
