### ISSUE TITLE
0.2.4 login() is breaking - Throws Nonsensical Error on Login Button Location

### ISSUE THREAD

**Issue by OldishCoder** [mkhorasani/Streamlit-Authenticator#109]
I was just setting up a new venv and decided to upgrade to the new release.
Unfortunately, code that was working broke with:
```
File "D:\my.py", line 102, in <module>
authenticator.login('Login', 'sidebar')
File "D:\temp\conda\envs\StreamServe\lib\site-packages\streamlit_authenticator\authenticate.py", line 240, in login
raise ValueError("Location must be one of 'main' or 'sidebar'")
ValueError: Location must be one of 'main' or 'sidebar'
```

I reverted to 0.2.3 and the error went away

Looking at the code authenticator.py line 211 shows the issue. The call syntax is new and different and is breaking.
Did we intend to break old code with this change?

**Comment by mkhorasani** [comment]
Hi @OldishCoder, please follow the readme file [here](https://github.com/mkhorasani/Streamlit-Authenticator?tab=readme-ov-file#parameters-1). In the latest release (v0.2.4), the form_name parameter has been removed from the widget and instead has been replaced with a fields parameter that enables you to customize any or all of the text fields in the form. I will remove this release and prepare a new one with a deprecation warning.
