### ISSUE TITLE
Will there be a v1.0.0 release?

### ISSUE THREAD

**Issue by BroderPeters** [mkhorasani/Streamlit-Authenticator#112]
I've been looking into this project a bit and got a bit curious about it's long term plans. The package seems to have a solid user base and is often stated to be ready to be used in production.

Looking at the semantic versioning, I've been wondering whether the project has passed its initial development phase or if there are still concrete steps to be done/taken until v1.0.0?

Here are the references where my question is based on:
https://semver.org/#how-should-i-deal-with-revisions-in-the-0yz-initial-development-phase
https://semver.org/#how-do-i-know-when-to-release-100

**Comment by mkhorasani** [comment]
Dear @BroderPeters, this is an excellent point and it's something that I've been wondering about for some time myself as well. Given the fact that some users are probably already using this in production and I am indeed constantly worried about back compatibility, then I guess it's pseudo-stable already. I'm probably going to hold out though on taking this plunge as I'm currently in the process of enacting a series of new features that are probably better off being released at the same time as v1.0.0. Until then I appreciate your patience and support, and please stay tuned for more to come!

**Comment by BroderPeters** [comment]
Thanks for the very valid response!
Looking forward to future changes and improvements!
