### ISSUE TITLE
new release v0.3.0 is causing the build to fail since it uses requests as a dependency

### ISSUE THREAD

**Issue by neeagl** [mkhorasani/Streamlit-Authenticator#116]

**Comment by mkhorasani** [comment]
Dear @neeagl, I believe this problem is associated with your runtime environment/server. While I am importing requests in this package, it is not being used to run the logic of the authentication. I recommend you re-install your packages to solve this issue.

**Comment by neeagl** [comment]
I am using the Github Actions to deploy this to Azure Web Apps but its failing, something has broken here
<img width="1288" alt="Screenshot 2024-01-26 at 1 58 06 AM" src="https://github.com/mkhorasani/Streamlit-Authenticator/assets/902759/e58cfb64-f344-4277-9881-78cc064b00f2">

**Comment by mkhorasani** [comment]
@neeagl please download v0.3.1 that was just released, it should resolve this issue.
