### ISSUE TITLE
Improve error message for registration

### ISSUE THREAD

**Issue by fsmosca** [mkhorasani/Streamlit-Authenticator#118]
I set domain to yahoo.com and tried to register using gmail. Got the error message below.

```
def get_register(authenticator):
    try:
        if authenticator.register_user(
            location='main',
            preauthorization=False,
            domains=['yahoo.com'],
            fields={'Form name': 'Register user'}
        ):
            save_config_to_deta(config)
            st.success('Registration is successful!')
    except Exception as e:
        st.error(e)
```

![image](https://github.com/mkhorasani/Streamlit-Authenticator/assets/22366935/0eabebb7-9951-44d0-a168-6010088db702)

To improve the error message, perhaps you need to mention that only the domains found in **domains** are supported. In this case, only yahoo. The reason is to inform the users of the real reason why their emails are not accepted.

It can be:

`Only emails from {domains} are supported.`

### Setup
* streamlit-authenticator 0.3.1

**Comment by mkhorasani** [comment]
@fsmosca you can also display your own customized error message with the except block if you like.
