### ISSUE TITLE
Fix the sample code in user registration.

### ISSUE THREAD

**Issue by fsmosca** [mkhorasani/Streamlit-Authenticator#119]
### Old

```python
try:
    if authenticator.register_user(preauthorization=False):
        st.success('User registered successfully')
except Exception as e:
    st.error(e)
```

### Update

```python
try:
    email, username, name = authenticator.register_user(
        location='main',
        preauthorization=False,
        domains=None,  # ['gmail.com', 'yahoo.com']
        fields={'Form name': 'Register User'}
    )
    if None not in (email, username, name):
        st.success('User registered successfully')
except Exception as e:
    st.error(e)
```

Also fix the return value of `register_user()` in the authenticate module.

**Comment by mkhorasani** [comment]
@fsmosca I'm not sure I understand what the issue is over here?

**Comment by fsmosca** [comment]
In the readme of this repo we have this currently.

![image](https://github.com/mkhorasani/Streamlit-Authenticator/assets/22366935/d8290658-1ea7-42f5-8188-3a778b229b08)


In the source code, it is still bool.

![image](https://github.com/mkhorasani/Streamlit-Authenticator/assets/22366935/c968fc87-0bc3-4256-ab75-f47ccdd267ff)

**Comment by mkhorasani** [comment]
Thanks for pointing this out.
