### ISSUE TITLE
Any way to enable enter key?

### ISSUE THREAD

**Issue by yanghoonkim** [mkhorasani/Streamlit-Authenticator#12]
Hi,
I want to press the enter key on the keyboard for authentication instead of clicking the login button.
Any way to enable this function?

**Comment by voidel** [comment]
Sorely needed!

**Comment by mkhorasani** [comment]
Hi @yanghoonkim, this feature has been enabled in release [v0.2.4](https://github.com/mkhorasani/Streamlit-Authenticator/releases/tag/v0.2.4). With Streamlit >= 1.25.0 this feature comes by default for all forms.
