### ISSUE TITLE
Installing Streamlit-Authenticator in Conda

### ISSUE THREAD

**Issue by Nando7789** [mkhorasani/Streamlit-Authenticator#120]
Hi, I'm Having issues to install this library in Anaconda V2.5.2 . I can't find it in any repository Conda has and I don't know if there is a shortcut to install it from git directly with Conda.

Best Regards!

**Comment by mkhorasani** [comment]
Please try to it install it via pip.Sent from my iPhoneOn Jan 26, 2024, at 4:08 PM, Nando7789 ***@***.***> wrote:﻿
Hi, I'm Having issues to install this library in Anaconda V2.5.2 . I can't find it in any repository Conda has and I don't know if there is a shortcut to install it from git directly with Conda.
Best Regards!

**Comment by Nando7789** [comment]
Ok I did it but this was because I see that could be errors using conda and pip at the same time.

Best regards!
