### ISSUE TITLE
DeprecationError: the 'form_name' parameter has been replaced with the 'fields' parameter in Streamlit.

### ISSUE THREAD

**Issue by styliann-eth** [mkhorasani/Streamlit-Authenticator#123]
<img width="1589" alt="Screenshot 2024-01-30 at 19 29 02" src="https://github.com/mkhorasani/Streamlit-Authenticator/assets/34973295/ded7fc5d-089d-4fe7-9bf3-b2c9078d895d">

Getting the above error when I run my streamlit dashboard. Having searched through the code, I don't use 'form_name' anywhere.

Has anyone encountered that error with streamlit-authenticator?

**Comment by mkhorasani** [comment]
Hi @styliann-eth, can you please share a snippet of your code?

**Comment by styliann-eth** [comment]
Thanks for getting back to me on this. I didn't realize that the arguments of the function had changed. Cheers.
