### ISSUE TITLE
Missing "submit button" error and TypeError: string indices must be integers (using streamlit)

### ISSUE THREAD

**Issue by MaxSeck** [mkhorasani/Streamlit-Authenticator#127]
Error: Missing Submit Button
This form has no submit button, which means that user interactions will never be sent to your Streamlit app.
To create a submit button, use the st.form_submit_button() function."

TypeError: string indices must be integers:
name, loginstate, username = authenticator.login(fields ='Login')  --> implemented (fields='Login') 
if login_form.form_submit_button('Login' if 'Login' not in fields else fields['Login']):

I think the issues came with the update to 0.3.1. Somebody with the same problems here?

**Comment by mkhorasani** [comment]
Dear @MaxSeck the fields parameter is dictionary and not a str. Please follow the documentation found [here](https://github.com/mkhorasani/Streamlit-Authenticator?tab=readme-ov-file#authenticatelogin). You will need to provide the fields parameter as follows:
```
authenticator.login(fields={'Form name':'Login', 'Username':'Username', 'Password':'Password', 'Login':'Login'})
```

**Comment by MaxSeck** [comment]
Thank you a lot @mkhorasani. That fixed my problem!
