### ISSUE TITLE
compatibility issue with chrome extension

### ISSUE THREAD

**Issue by yanghoonkim** [mkhorasani/Streamlit-Authenticator#13]
Hi,

I found that if I enable the evernote clipper in the chrome, I can't login for some reason, and nothing is  displayed in the terminal.

Other extension have nothing to do with the compatibility issue.

Would you please check it out?

**Comment by mkhorasani** [comment]
Hi @yanghoonkim, I am unable to recreate this issue, perhaps it is unrelated. Please try to update to the latest version [v0.2.4](https://github.com/mkhorasani/Streamlit-Authenticator/releases/tag/v0.2.4) and let me know if the problem persists. Thanks.
