### ISSUE TITLE
logout

### ISSUE THREAD

**Issue by jgperrin** [mkhorasani/Streamlit-Authenticator#136]
How can I control the logout?

1. When I logout and login again, the chat is still there. How can I clear everything?

2. How can I logout via a function? Like if there is an emergency?

**Comment by mkhorasani** [comment]
Dear @jgperrin, please refer to the [README](https://github.com/mkhorasani/Streamlit-Authenticator?tab=readme-ov-file#authenticatelogout) for further information about how to invoke the logout feature.
1. I am not sure what exactly you mean by 'the chat is still there'? In Streamlit, widgets are stateful within the same session, i.e. if you do not refresh your webpage then anything you have entered will still be there.
2. You can programmatically logout by passing `location='unrendered'` to the logout feature.
