### ISSUE TITLE
When I click lagout to log out, and log-in again,  My interface cannot load,  help me,  please

### ISSUE THREAD

**Issue by likescentific** [mkhorasani/Streamlit-Authenticator#138]
![image](https://github.com/mkhorasani/Streamlit-Authenticator/assets/157553372/a79a83af-0fb3-4d62-a33a-126828c0adf8)

![image](https://github.com/mkhorasani/Streamlit-Authenticator/assets/157553372/6caa1aa0-6634-44bd-979c-99986d9bf297)

**Comment by mkhorasani** [comment]
Can you please share your source code?

**Comment by mkhorasani** [comment]
Apologies, but I will be closing this issue for the meantime until further information is provided.
