### ISSUE TITLE
Newer version breaks with cookies from old version

### ISSUE THREAD

**Issue by charlielito** [mkhorasani/Streamlit-Authenticator#14]
Hi, I was using version 0.1.0, and when updated to version 0.1.4, because I and other users already have some cookies in the browsers, the code breaks when it tries to access the field `username` from the cookies.

The traceback is
```
File "/code/app/utils/misc.py", line 35, in authentication_workflow
    name, authentication_status, username = authenticator.login("Login", "sidebar")
File "/usr/local/lib/python3.8/site-packages/streamlit_authenticator/__init__.py", line 163, in login
    st.session_state['username'] = self.token['username']
```

**Comment by mkhorasani** [comment]
Hi @charlielito, that is correct in v0.1.0 the username was not being committed to the cookie, however as of v0.1.4 it is. Therefore an older cookie will trigger an error as you pointed out. I recommend you either delete the associated cookie, or simply rename your cookie to avoid any errors.

**Comment by charlielito** [comment]
> Hi @charlielito, that is correct in v0.1.0 the username was not being committed to the cookie, however as of v0.1.4 it is. Therefore an older cookie will trigger an error as you pointed out. I recommend you either delete the associated cookie, or simply rename your cookie to avoid any errors.

what if the library handles this? :smile:

**Comment by mkhorasani** [comment]
Please refer to v0.1.5 (just released) for this fix.
