### ISSUE TITLE
Confirm logout message

### ISSUE THREAD

**Issue by skannan-maf** [mkhorasani/Streamlit-Authenticator#142]
Originally here: https://discuss.streamlit.io/t/streamlit-authenticator-logout-are-you-sure-message/64125

My requirement is to ensure there is a confirmation message shown before the actual logout?
How can I do this?

**Comment by mkhorasani** [comment]
Hi @skannan-maf, thank you for reaching out. You can implement your own customized logout function by using Streamlit-Authenticator's renderless logout capability as shown [here](https://github.com/mkhorasani/Streamlit-Authenticator?tab=readme-ov-file#authenticatelogout)in the readme. By passing the parameter `location='unrendered'` to the logout function, you can logout without showing the logout widget and instead develop your own logout mechanism/form to interface with the logic. Hope this helps!

**Comment by skannan-maf** [comment]
Vow! Thats a great design! Thanks a lot!

**Comment by skannan-maf** [comment]
@mkhorasani  Thanks for your solution. I have also updated the streamlit thread. Thanks again!

**Comment by mkhorasani** [comment]
Thank you!
