### ISSUE TITLE
logout() requires browser window reload

### ISSUE THREAD

**Issue by darshitsharma** [mkhorasani/Streamlit-Authenticator#145]
Hi,

I am using ```logout()``` option in the code given below. The functionality is fine, it clears the session states but to render the ```login()``` again I have to refresh the browser window. Could anyone help in this case?

![image](https://github.com/mkhorasani/Streamlit-Authenticator/assets/25049594/5f01dd23-5254-4e47-aec9-6b2048d2e336)

**Comment by mkhorasani** [comment]
Hi @darshitsharma, I'm not exactly sure why this is happening but perhaps you can use the following piece of code to remedy it:
`
if st.button('Logout'):
   authenticator.logout(location='unrendered')
   st.experimental_rerun()
`
