### ISSUE TITLE
Login not disappearing, imports not working, register not writing

### ISSUE THREAD

**Issue by JustinGuese** [mkhorasani/Streamlit-Authenticator#148]
Hey, not sure if this is still maintained... but I am experiencing multiple issues

- The login window remains shown even if the user is logged in
- I can't import from local files anymore when using the library
- In every page (register, login, reset...) I need to reininitialize the authenticator as I can't import it from anywhere
- Sometimes all pages show in the main app (register, login, ...)

Is this normal? Using a new pydantic env, Python 3.11, Mac

**Comment by mkhorasani** [comment]
Hi @JustinGuese, can you please share your source code and let me know which version of Streamlit-Authenitcator you're using?

**Comment by mkhorasani** [comment]
Apologies, but I will be closing this issue for the meantime until further information is provided.
