### ISSUE TITLE
Get passwords from Database

### ISSUE THREAD

**Issue by aYoHoldings** [mkhorasani/Streamlit-Authenticator#15]
Hi,

I am trying to get my passwords with  a select query from the database, but when I pass it to the Hasher module, I get an error:

File "/home/appuser/venv/lib/python3.9/site-packages/streamlit_authenticator/__init__.py", line 37, in hash

    return bcrypt.hashpw(password.encode(), bcrypt.gensalt()).decode()

AttributeError: 'tuple' object has no attribute 'encode'

What type of object should be passed to the Hasher module?

I am very new to python and will appreciate your help tremendously.

**Comment by mkhorasani** [comment]
Hi,

Please pass your passwords ONLY as a list of strings, i.e. ['123', '456'] not as a tuple or any other data structure.
