### ISSUE TITLE
Email verification after registration

### ISSUE THREAD

**Issue by harsh9898** [mkhorasani/Streamlit-Authenticator#150]
Hey @mkhorasani 

This package is awesome and it helps me and saves a lot of time and effort. Thank you so much for building such a great package.

One thing that I wanted to figure out is how can I make sure that the user is entering the email exists(no dummy emails). The reason I ask this is let's say some user has put abc123@gmail.com, it will accept and register the user. But I have implemented sending emails for `reset password` and `forgot the user name`. In those cases, they won't receive any emails as the email itself does not exist in the real world.

Can you please give me some idea on how to achieve this? If you can implement some way to verify the email address in ***register_user*** function then nothing like it.

Thank you,
Harsh

**Comment by mkhorasani** [comment]
Hi @harsh9898, thank you for reaching out! Sure, I will look into implementing this for a future release.
