### ISSUE TITLE
To force user to use stonger password when they register

### ISSUE THREAD

**Issue by scutccli** [mkhorasani/Streamlit-Authenticator#153]
Currently, it seems not so safe because user is able to key in anything as password. It is better force user to use strong password such as:
(1) Must be more than 8 digits
(2) Include at least one symbol
(3) In clude at least one upper case and lower case letter and number.
Maybe can consider this in next update.

**Comment by mkhorasani** [comment]
Hi @scutccli, this is a great idea. I will add a `validate_password` method to the validator class, and also leave it open to the developer to specify their own validations for a future release.

**Comment by scutccli** [comment]
Hi @mkhorasani, that's great! Thanks

**Comment by mkhorasani** [comment]
Done! Please refer to [v0.3.3](https://github.com/mkhorasani/Streamlit-Authenticator/releases/tag/v0.3.3).
