### ISSUE TITLE
Captcha verification

### ISSUE THREAD

**Issue by tolgaduzenli** [mkhorasani/Streamlit-Authenticator#154]
Is there a way yo add captcha verification to the login page?

**Comment by mkhorasani** [comment]
Hi @tolgaduzenli, not as of now, perhaps I can look into it for a future release.

**Comment by mkhorasani** [comment]
Done! Please refer to [v0.3.3](https://github.com/mkhorasani/Streamlit-Authenticator/releases/tag/v0.3.3).
