### ISSUE TITLE
Refresh Page Would Lost Login and the way to fix it 

### ISSUE THREAD

**Issue by qiang-yu** [mkhorasani/Streamlit-Authenticator#159]
version    streamlit-authenticator==0.3.2

I have read the document which only says  "**Multi Page**" you need to call authenticator.login() in every Page 

But , i have only single page,  my problem is , every time i refresh the browser,  the page would throw an exception "authentication_status  not in  st.session_state"

Here is the way to fix this problem :

**streamlit_authenticator\authenticate\\__init__.py** 

![Screenshot_3](https://github.com/mkhorasani/Streamlit-Authenticator/assets/5996702/e526d5b0-56ed-4e0e-ad55-674dbcd6921c)

**streamlit_authenticator\authenticate\cookie\\__init__.py** 

![Screenshot_2](https://github.com/mkhorasani/Streamlit-Authenticator/assets/5996702/6323fd05-34db-45fc-8a0f-10c7ffb612b8)

Just Change these two lines , and you can Refresh your page now , eveything is OK 

Hope you guys can fix this bug in next release

thanks

**Comment by mkhorasani** [comment]
Hi @qiang-yu, the first part is already implemented as shown below: 
![image](https://github.com/mkhorasani/Streamlit-Authenticator/assets/38884731/a4567184-026c-4476-bf93-29936e3d65b7)

The second part I will add and release in a future version.
