### ISSUE TITLE
Does the session parameters remain as is even after reloading the page?

### ISSUE THREAD

**Issue by aadarshsingh191198** [mkhorasani/Streamlit-Authenticator#16]
I tried implementing a login myself. It uses the session variables to do the authentication just like you mentioned in your medium blog. But on reloading the page, the session variables go away, and thus the user is logged out. So, have you handled that in this library?

**Comment by mkhorasani** [comment]
Yes that is correct, when you reload the page a new Streamlit session is created and all session state variables from the previous session are reset (including the login state), that is why this library is using cookies to store authentication parameters persistently on the client's browser. As long as you set the cookie_expiry_days > 0, then you should face no problems with automatic reauthentication.
