### ISSUE TITLE
Typo in README.md in Authenticate.register_user(): pre-authorization => pre_authorization

### ISSUE THREAD

**Issue by tigran123** [mkhorasani/Streamlit-Authenticator#160]
The subject says it: in `Authenticate.register_user()` method documentation the parameter `pre_authorization` is misspelled as `pre-authorization` (which is not a valid Python identifier anyway).

Thank you for the excellent Streamlit-Authenticator tool and a very interesting book, which I am now reading.

**Comment by mkhorasani** [comment]
Hi @tigran123, thank you for bringing this to my attention! I will fix and push it in the next release. You are most welcome, and I'm glad that you find the book interesting. Cheers!
