### ISSUE TITLE
Add callback options for widgets

### ISSUE THREAD

**Issue by agomezh** [mkhorasani/Streamlit-Authenticator#161]
Add a callback option for the widgets.

I think this is a possible way to interact with the database, so when the login widget is clicked, a callback function can interact with the database (to connect remotely, save to yaml, etc.). 

Or even other events.

**Comment by mkhorasani** [comment]
Done! Please refer to [v0.3.3](https://github.com/mkhorasani/Streamlit-Authenticator/releases/tag/v0.3.3).
