### ISSUE TITLE
DeprecationError: Likely deprecation error, the 'form_name' parameter has been replaced with the 'fields' parameter.

### ISSUE THREAD

**Issue by Solab5** [mkhorasani/Streamlit-Authenticator#162]
was following though the github instructions, but the authenticator.login() can't execute coz of a depraction error

![Image 13-05-2024 at 12 22](https://github.com/mkhorasani/Streamlit-Authenticator/assets/78223861/3bac0d60-f3fc-4d43-9c41-d720a3a84ca4)

**Comment by mkhorasani** [comment]
Please follow the instructions as provided in the link. The form name should be provided in the form of a dictionary as shown below:
```
authenticator.login(fields={'Form name':'Login', 'Username':'Username', 'Password':'Password', 'Login':'Login'})
```
