### ISSUE TITLE
add firebase capability

### ISSUE THREAD

**Issue by iuiu34** [mkhorasani/Streamlit-Authenticator#163]
Hi,
would be possible to add the option to login with firebase? without the yaml config file?

Basically, would be adding [this ](https://gist.github.com/cquangc/1b0d6cf08fe250a680d1d823eff7701b) capability.
But this way all authentication methods in st are unified in a single component.

thanks

**Comment by mkhorasani** [comment]
Hi @iuiu34, thank you for reaching out. You'll be delighted to know that this feature is already in the works, and I anticipate releasing it within the next several months.

**Comment by iuiu34** [comment]
lovely, thanks!

**Comment by mkhorasani** [comment]
Since this issue was previously raised, I request that you kindly follow the developments on #42.
