### ISSUE TITLE
Forgot password and forgot username components

### ISSUE THREAD

**Issue by kayozxo** [mkhorasani/Streamlit-Authenticator#165]
Forgot password and username components do nothing when I provide what it asks. It's been over an hour, and I received no mail. But when I fill in the required field and press enter, it shows **New password to be sent securely**

**Comment by mkhorasani** [comment]
Please note that the developer should send the forgotten username/password to the user using their own means. The package will not take care of this.

![image](https://github.com/mkhorasani/Streamlit-Authenticator/assets/38884731/56905127-9874-4434-8692-9fd6e0862b69)
