### ISSUE TITLE
Logout takes a lot of time when there is more data in the application's session state.

### ISSUE THREAD

**Issue by harsh9898** [mkhorasani/Streamlit-Authenticator#166]
I have implemented the authentication module in my application and it works great. The only thing is Logout takes an ample amount of time when there is a significant amount of session data. This is because of streamlit's top-down execution model whenever there is some user interaction. Moreover, it is better to delete all the session key data on the click of logout instead of just the session keys set by the streamlit authenticator module.

I have a solution and would like to contribute by creating the pull request.

Thank you so much for creating such a great and easy-to-use authentication module for streamlit. Keep it up.

**Comment by mkhorasani** [comment]
Hi @harsh9898, thank you for reaching out. I understand the concern here, and the good news is that the next release for this package will include a callback argument for all the widgets which will enable you to implement any additional logic on top of what already exists. Please stay tuned!
