### ISSUE TITLE
DuplicateWidgetID: There are multiple identical st.button widgets with the same generated key.

### ISSUE THREAD

**Issue by jitvimol** [mkhorasani/Streamlit-Authenticator#17]
When following and try running code from github.  Everything function except there's an error of streamlit.  

My Analysis and solution:  st.button widget required assigned "different" keyname  and the backend code use the same keyname, resulting in an error.  

error msg from cli:
''' 
streamlit.errors.DuplicateWidgetID: There are multiple identical `st.button` widgets with the
same generated key.

When a widget is created, it's assigned an internal key based on
its structure. Multiple widgets with an identical structure will
result in the same internal key, which causes this error.

To fix this error, please pass a unique `key` argument to
`st.button`.
'''

![SNAG-0086](https://user-images.githubusercontent.com/13816717/172532114-060072d5-b46b-495e-8db7-11c2087e6974.png)

**Comment by mkhorasani** [comment]
Please ensure that you have no duplicate 'logout' buttons that have the exact same name as the ones being used for the login form.
