### ISSUE TITLE
No middle name or initials are allowed by authenticator.register_user()

### ISSUE THREAD

**Issue by tigran123** [mkhorasani/Streamlit-Authenticator#171]
If "John F. Smith" is not a valid name, then I don't know what is :)

Seriously, here is a screenshot:

![image](https://github.com/mkhorasani/Streamlit-Authenticator/assets/1933903/7124908f-d6c8-4824-8c2c-d12592b6e88a)

If I remove the middle initial "F." then of course it will be valid, but the whole point is that the user may wish to have his full name, including any middle initials, to be recorded in the registration data. So this is a bug.

**Comment by tigran123** [comment]
I can see in the source code in the `Validator` class here:

https://github.com/mkhorasani/Streamlit-Authenticator/blob/61d7adcb9d7a8c004705607d408be2b7cd425670/streamlit_authenticator/utilities/validator.py#L47

that it is due to the pattern `^[A-Za-z ]+$` not including a dot.

**Comment by tigran123** [comment]
Thank you. Is there an example code of how to pass my own Validator object when instantiating `stauth.Authenticate()`?

**Comment by mkhorasani** [comment]
Unfortunately no, just please create a validator object of your own using the exact structure shown in this [file](https://github.com/mkhorasani/Streamlit-Authenticator/blob/main/streamlit_authenticator/utilities/validator.py).

**Comment by tigran123** [comment]
Ok, yes, that sounds simple enough -- initially I was worried due to the size, but upon reading the whole code I realised that most of it was comments. Thanks again!
