### ISSUE TITLE
How do I execute logout button logic?

### ISSUE THREAD

**Issue by moruga123** [mkhorasani/Streamlit-Authenticator#172]
If authentication_status is True, I display a logout button.

If I log out, the logout button python variable will not be defined because authentication_status is False upon rerunning the script. Therefore, I can't implement any logout logic.

I need access to the username that just logged out, to do the logout logic as well.

**Comment by mkhorasani** [comment]
Hi @moruga123, in the next release of Streamlit-Authenticator, a callback argument will be included with every widget including the logout button so that developers can implement any additional logic on top of the logic of the package itself. Please stay tuned!
