### ISSUE TITLE
Web Blank line with the Authenticator Class

### ISSUE THREAD

**Issue by lhcaloi** [mkhorasani/Streamlit-Authenticator#177]
Hi, I would appreciate it if anyone can help me. When I choose a page in the menu on the left (I'm using pages of streamlit) that has a call to Authenticator Class initialization, it is possible to notice in the panel on the right on the web screen that a blank line is created. Is there any way for this not to happen?

**For example:**
import streamlit as st
from auth import Authenticator

auth = Authenticator()

auth.check_auth()

st.title("Home Page")
st.write("This is the home page.")

**Comment by mkhorasani** [comment]
Hi @lhcaloi, I highly doubt that this is related to Streamlit-Authenticator. To the best of my knowledge, there are no `st.write` functions that would write anything including a blank line to your web page.

**Comment by lhcaloi** [comment]
I created a simple example to show you what happend. Take a look at the situation below. Whenever you click on the Option 1 or Option 2 menu, it will create the blank space in the web view. The line will flash on the screen.

app
  pages
    1_Option_2.py
 0_Option_1.py
 auth.py
 config.yaml

**auth.py**
```
import streamlit as st
import streamlit_authenticator as stauth
import yaml
from yaml.loader import SafeLoader
from streamlit_authenticator import LoginError

def function_authenticator():
    try:
        config_path = 'app/config.yaml'
        with open(config_path) as file:
            config = yaml.load(file, Loader=SafeLoader)

        authenticator = stauth.Authenticate(
            config['credentials'],
            config['cookie']['name'],
            config['cookie']['key'],
            config['cookie']['expiry_days'],
            config['pre-authorized']
        )

        authenticator.login()

        name, authentication_status, username = authenticator.login()

        if authentication_status is True:
            return True

    except LoginError as error:
        print(error)

```
**0_Option_1.py**
```
import streamlit as st

from auth import function_authenticator

test  = function_authenticator()

if test:
    st.write("You are logged in!")

```
**0_Option_2.py**
```
import streamlit as st

from auth import function_authenticator

test = function_authenticator()

if test:
    st.write("You are logged in!")
    
```
**config.yml**
cookie:
  expiry_days: 30
  key: testetesteteste
  name: some_cookie_name
credentials:
  usernames:
    admin:
      email: dbaldwin@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: David Baldwin
      password: $2b$12$.GMLKX.PPOWAAY.RxgIZiOYvYk8clY9rQdktg24bhLA9GkRR4yzu.
pre-authorized:
  emails:
  - melsby@gmail.com

Streamlit, version 1.36.0

**Comment by dbux** [comment]
Easiest solution to this I have found is to render the `Authenticate` component inside a `st.empty` container that can be cleared after a successful login.

For example:
```python
    empty = st.empty()
    
    with empty:
        authenticator = Authenticate()

    if st.session_state.get("authentication_status"):
        empty.empty()
```
