### ISSUE TITLE
Why sleep in login()?

### ISSUE THREAD

**Issue by wanderor** [mkhorasani/Streamlit-Authenticator#178]
Thanks for this great library! Really appreciated.

I wonder why there is a sleep call in `Authenticate.login()`, `streamlit_authenticator/authenticate/__init__.py` (version 0.3.2):

```
            token = self.cookie_handler.get_cookie()
            if token:
                self.authentication_handler.execute_login(token=token)
            time.sleep(0.7)
```

I located this line when I was debugging an issue in my app: the first login attempt never works; user always need to fill in and submit the login form a second time. After I removed this line, everything seems to work just fine, and I notice no side effect.

**Comment by mkhorasani** [comment]
Dear @wanderor, the `sleep` function was added to prevent latency issues as pointed out here https://github.com/mkhorasani/Streamlit-Authenticator/issues/124. Please note that in the next release I will add the option for the user to upload hyperparameters such as this sleep time as a config.toml file to the package.

**Comment by wanderor** [comment]
Thank you for your prompt response. Indeed, I am seeing the flashing login form now after removing that sleep. OTOH, I consider it a small, tolerant issue, compared to the issue that user always need to fill in and submit the login form a second time as I previously mentioned. Strange. I will let you know if I find anything.

**Comment by mkhorasani** [comment]
Dear @wanderor, the `sleep_time` parameter has now been added to the login widget, please refer to the latest release [v0.3.3](https://github.com/mkhorasani/Streamlit-Authenticator/releases/tag/v0.3.3).
