### ISSUE TITLE
NameError: name 'SafeLoader' is not defined

### ISSUE THREAD

**Issue by jitvimol** [mkhorasani/Streamlit-Authenticator#18]
ymal config loader might depreciated?  I try running the code and there's an error about "Loader=SafeLoader"  I switch to new code below and found working.

with open('user.ymal') as file:
    # config = yaml.load(file, Loader=SafeLoader)   # previous code, not working
    config = yaml.safe_load(file)   # new code (working)

![SNAG-0087](https://user-images.githubusercontent.com/13816717/172532838-4914032d-443e-407e-8cfa-e2fce868bd73.png)

**Comment by mkhorasani** [comment]
Yes please ensure you are using PyYAML >= 5.3.1. Regards.

**Comment by batmanscode** [comment]
Hi @mkhorasani I'm having this same issue even after upgrading PyYAML

**Comment by batmanscode** [comment]
> Hi @mkhorasani I'm having this same issue even after upgrading PyYAML

Worked after I added `from yaml import SafeLoader`

**Comment by blacklistseller** [comment]
> > Hi @mkhorasani I'm having this same issue even after upgrading PyYAML
> 
> Worked after I added `from yaml import SafeLoader`

Confirmed that it's solved.  Thank you!

**Comment by jitvimol** [comment]
> > Hi @mkhorasani I'm having this same issue even after upgrading PyYAML
> 
> Worked after I added `from yaml import SafeLoader`

Confirm that it works.  Thank you!
