### ISSUE TITLE
Page refreshes rapidly forever

### ISSUE THREAD

**Issue by egelados** [mkhorasani/Streamlit-Authenticator#180]
I m using the following:

```
import streamlit as st
import yaml
from yaml.loader import SafeLoader
import streamlit_authenticator as stauth


st.set_page_config(page_title="Home", page_icon="", layout="wide")

with open('./usersdb.yaml') as file:
    config = yaml.load(file, Loader=SafeLoader)

authenticator = stauth.Authenticate(
    credentials=config["credentials"],
    cookie_name=config["cookie"]["name"],
    cookie_key=config["cookie"]["key"],
    cookie_expiry_days=config["cookie"]["expiry_days"],
    pre_authorized=config["pre-authorized"],
)
authenticator.login()

if "authenticator" not in st.session_state:
    st.session_state.authenticator = authenticator

if st.session_state["authentication_status"] == False:
    st.error("Username/password is incorrect")


if st.session_state["authentication_status"]:
    st.info("Successful login")
```
    

The platform is docker on macbook with streamlit_authenticator 0.3.3 and streamlit 1.37

The symptoms are:
- If i enter the credentials correctly one time nothing happens. 
- If i enter the credentials correctly a second time the app enters an endless loop of rapid refresh where i can see in the side bar the logout button flashing with the rest of sidebar really-really fast.

(It would be really helpful if you provided a simple working example in the documentation to use out of the box)

**Comment by mkhorasani** [comment]
Dear @egelados, please follow the example provided in the [readme](https://github.com/mkhorasani/Streamlit-Authenticator/blob/main/README.md). Alternatively please refer to this [demo](https://demoapp-v0-3-3.streamlit.app/), you can find the source code for it [here](https://github.com/mkhorasani/Streamlit-Authenticator-demo/blob/main/streamlit_authenticator_demo.py). Hope this helps!

**Comment by egelados** [comment]
Thanks for the prompt response. The demo app and its source code was indeed helpful. It works out of the box and showcases exactly how streamlit authenticator should be used.

**Comment by mkhorasani** [comment]
Glad it helped!
