### ISSUE TITLE
Error Username/password is incorrect

### ISSUE THREAD

**Issue by vladyskai** [mkhorasani/Streamlit-Authenticator#182]
I try using the demo app and also locally with my code. Even if the user is in the config.yaml file, it does not log in.

![image](https://github.com/user-attachments/assets/2fc96089-de88-4542-85db-1d2f2f165886)

**Comment by mkhorasani** [comment]
Hi @vladyskai, I guess some of the users trying out the demo app have reset the passwords :D. I will disable the `reset_password` widget on the demo app to avoid this issue. As for your local implementation can you please share your source code?

**Comment by Rohit036** [comment]
The same is happening for my local implementation. 

![image](https://github.com/user-attachments/assets/817327a6-803c-4305-9fbd-782ca4d8577a)


```

import yaml
import streamlit as st
from yaml.loader import SafeLoader
import streamlit_authenticator as stauth
from streamlit_authenticator.utilities import LoginError

# Loading config file
with open('config_user_pwd.yaml', 'r', encoding='utf-8') as file:
    config = yaml.load(file, Loader=SafeLoader)

# Hashing all plain text passwords once
# Hasher.hash_passwords(config['credentials'])

# Creating the authenticator object
authenticator = stauth.Authenticate(
    config['credentials'],
    config['cookie']['name'],
    config['cookie']['key'],
    config['cookie']['expiry_days'],
    config['pre-authorized']
)

# Creating a login widget
try:
    authenticator.login()
except LoginError as e:
    st.error(e)

if st.session_state["authentication_status"]:
    authenticator.logout()
    st.write(f'Welcome *{st.session_state["name"]}*')
    st.title('Some content')
elif st.session_state["authentication_status"] is False:
    st.error('Username/password is incorrect')
elif st.session_state["authentication_status"] is None:
    st.warning('Please enter your username and password')
```

**Comment by Rohit036** [comment]
> I try using the demo app and also locally with my code. Even if the user is in the config.yaml file, it does not log in.
> 
> ![image](https://private-user-images.githubusercontent.com/116801803/353411679-2fc96089-de88-4542-85db-1d2f2f165886.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MTk2ODcsIm5iZiI6MTcyMjQxOTM4NywicGF0aCI6Ii8xMTY4MDE4MDMvMzUzNDExNjc5LTJmYzk2MDg5LWRlODgtNDU0Mi04NWRiLTFkMmYyZjE2NTg4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMVQwOTQ5NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OTE2MjQ4ODE0NDc5YTVlOWFjOTY4Y2EwMzU2ZWU3NzlkOTVkYzZlNWM4N2Q0YmU1OTEyN2EzYTU0MWFlMDg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fogXND9JaR0cL8M03oGHnptY3oV6zGxss-Tzx8gwfKQ)

Just uncomment the following line for rehash the password. 

![image](https://github.com/user-attachments/assets/63886ca1-3205-46fa-a78c-477b9fd35e1b)

**Comment by vladyskai** [comment]
> Hi @vladyskai, I guess some of the users trying out the demo app have reset the passwords :D. I will disable the `reset_password` widget on the demo app to avoid this issue. As for your local implementation can you please share your source code?

My minimum reproducible example. Thank you very much!

```
import streamlit as st
import streamlit_authenticator as stauth
import yaml
from yaml.loader import SafeLoader

# Load configuration from YAML file
config_file_path = "config.yaml"

with open(config_file_path) as file:
    config = yaml.load(file, Loader=SafeLoader)

# Initialize the authenticator
authenticator = stauth.Authenticate(
    config["credentials"],
    config["cookie"]["name"],
    config["cookie"]["key"],
    config["cookie"]["expiry_days"],
    config["pre-authorized"],
)


# Function to update the config file
def update_config():
    with open(config_file_path, "w") as file:
        yaml.dump(config, file, default_flow_style=False)


# Create the login widget
name, authentication_status, username = authenticator.login(location="main")

if authentication_status:
    st.write(f"Welcome *{name}*")

    # Logout button
    authenticator.logout("Logout", location="sidebar")

    st.title("Some content")

    # Reset password widget
    if st.button("Reset Password"):
        try:
            if authenticator.reset_password(username):
                st.success("Password modified successfully")
                update_config()
        except Exception as e:
            st.error(e)

    # Update user details widget
    if st.button("Update User Details"):
        try:
            if authenticator.update_user_details(username):
                st.success("Entries updated successfully")
                update_config()
        except Exception as e:
            st.error(e)

elif authentication_status is False:
    st.error("Username/password is incorrect")

elif authentication_status is None:
    st.warning("Please enter your username and password")
```

**Comment by vladyskai** [comment]
> > I try using the demo app and also locally with my code. Even if the user is in the config.yaml file, it does not log in.
> > ![image](https://private-user-images.githubusercontent.com/116801803/353411679-2fc96089-de88-4542-85db-1d2f2f165886.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MTk2ODcsIm5iZiI6MTcyMjQxOTM4NywicGF0aCI6Ii8xMTY4MDE4MDMvMzUzNDExNjc5LTJmYzk2MDg5LWRlODgtNDU0Mi04NWRiLTFkMmYyZjE2NTg4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMVQwOTQ5NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OTE2MjQ4ODE0NDc5YTVlOWFjOTY4Y2EwMzU2ZWU3NzlkOTVkYzZlNWM4N2Q0YmU1OTEyN2EzYTU0MWFlMDg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fogXND9JaR0cL8M03oGHnptY3oV6zGxss-Tzx8gwfKQ)
> 
> Just uncomment the following line for rehash the password.
> 
> ![image](https://private-user-images.githubusercontent.com/1837507/353784372-63886ca1-3205-46fa-a78c-477b9fd35e1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MjAzNjIsIm5iZiI6MTcyMjQyMDA2MiwicGF0aCI6Ii8xODM3NTA3LzM1Mzc4NDM3Mi02Mzg4NmNhMS0zMjA1LTQ2ZmEtYTc4Yy00NzdiOWZkMzVlMWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDczMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MzFUMTAwMTAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzM3MGNmYWEwYTQ5YTEwNGI0N2ZiODEwYWM5NWU5MGVjZmJmNDg3M2E0ODQ2OGViOGY5ZjZiMDVkNjZlM2VmMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.v55vFaXBoDRMOBltJSbz4N1WNWY_Ma3AnQYpoXeBRQ4)

Thank you very much! This worked! I believe this means that the "auto_hash" part of the code is not working properly.

**Comment by mkhorasani** [comment]
The `auto_hash` feature does work, I just retested it. Please do a hard refresh of your application, since the auto_hash feature will only work once per session.

**Comment by vladyskai** [comment]
I believe I understood the issue. In the config.yaml file, instead of putting:
`password: abc`
You shoud put the hashed version of this:
`password: $2b$12$QoHAb/x1adCxIXWZ7dJsJuVuCDM.g7eNfCI3/wyZSaj/6yj5cZxwq`

This can be obtained with this code:
```
import streamlit_authenticator as stauth

passwords = ["abc", "def"]
hashed_passwords = stauth.Hasher(passwords).generate()
print(hashed_passwords)
```
With this, my code works.
