### ISSUE TITLE
Invalid salt from 0.3.3

### ISSUE THREAD

**Issue by exallon72** [mkhorasani/Streamlit-Authenticator#186]
I am getting invalid salt all the time.

0.3.2 works as expected.

**Comment by mkhorasani** [comment]
Can you please check your config file to make sure that all the passwords are hashed? If not please use the `Hasher.hash_passwords` function to hash your passwords.

**Comment by chuong98** [comment]
Does that mean the `auto_harsh` option no longer works.?

**Comment by mkhorasani** [comment]
> Does that mean the `auto_harsh` option no longer works.?

It does work. I believe this issue may be happening due to an interference with session_state which I will address in the upcoming v0.3.4. Otherwise the `auto_hash` feature does work as expected.

**Comment by robinzimmermann** [comment]
I had the same problem and pre-hashing the passwords fixed it. Thanks!

**Comment by baswenneker** [comment]
I've upgraded form 0.3.2 and authentication stopped working. Got the message `invalid salt`. I added the Hasher.hash_passwords and it started working. Setting `auto_hash=True` in the Authenticate constructor didn't help.

Not sure why this ticket was closed. It is a bug in 0.3.3.

**Comment by geekypilot** [comment]
I'm afraid I'm experiencing exactly the same issue with 0.3.3.

Let's fix it, please.

**Comment by mkhorasani** [comment]
Please make sure you are saving the config file as per the last step of the readme. The passwords in the config file must be in hash form, not plain text, otherwise you will continue to face this error.
