### ISSUE TITLE
Password does not meet criteria

### ISSUE THREAD

**Issue by chuong98** [mkhorasani/Streamlit-Authenticator#187]
I tried with the version 0.3.3 but get the error when register new user.
Even if I overwrite the validator:
```python 
from streamlit_authenticator.utilities import  Validator
                                              
class MyValidator(Validator):
    def validate_password(self, password: str) -> bool:
        return True
auth = Authenticate(
    config['credentials'],
    config['cookie']['name'],
    config['cookie']['key'],
    config['cookie']['expiry_days'],
    config['pre-authorized'],
    validator=MyValidator(),
    auto_hash=True
)
```

**Comment by mkhorasani** [comment]
Hi @chuong98, this is indeed a bug, and I will fix it in the next release that should be released this month. Thank you for bringing this to my attention!

**Comment by chuong98** [comment]
Can you also provide the option to write Hint about the requirements of the password

**Comment by mkhorasani** [comment]
> Can you also provide the option to write Hint about the requirements of the password

Excellent idea! Will do.

**Comment by indrex** [comment]
Came here too share that I added a hint for users in the form explaining that only `!@$%*?&` are allowed. They kept trying underscore etc and I had no idea why the validation failed until I checked the regex in the validator method.

**Comment by mkhorasani** [comment]
Yes apologies for that, a fix is on the way!

**Comment by indrex** [comment]
@mkhorasani you are doing great, thanks for the project.

**Comment by mkhorasani** [comment]
> @mkhorasani you are doing great, thanks for the project.

You're most welcome.

**Comment by ironhak** [comment]
Hello I tried replicating the code in the main github readme file tutorial and I get this error. Is the fix coming? 
Thank's

**Comment by mkhorasani** [comment]
> Hello I tried replicating the code in the main github readme file tutorial and I get this error. Is the fix coming? Thank's

Yeap on the way!

**Comment by ironhak** [comment]
Thanks so much

**Comment by baswenneker** [comment]
A fix would be greatly appreciated.

**Comment by ironhak** [comment]
This also happens with "reset password widget".

**Comment by ironhak** [comment]
Any ETA regarding when a new release with the fix will come out?

**Comment by mkhorasani** [comment]
> Any ETA regarding when a new release with the fix will come out?

Fingers crossed by the end of the coming week.

**Comment by yjad** [comment]
Login is working but same message shows on reset_user. it also seems that the validation callback is always called regardless of the parameter.

**Comment by purushotaman748** [comment]
has the new version come out yet?

**Comment by ironhak** [comment]
> has the new version come out yet?

Nope. Still waiting.

**Comment by mkhorasani** [comment]
Apologies everyone for the delay but, I will need one more week. Much appreciated!

**Comment by briannewtonpsyd** [comment]
For anyone waiting on this fix, here's the regex being used:

^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,20}$

It is 8-20 characters, one lowercase letter, one uppercase, one number AND one special character (@$!%*?&). You can test it here:

https://regex101.com/

**Comment by mkhorasani** [comment]
Dear all, I just released the latest version, it addresses this issue. You can now provide a custom _Validator_ object to the _Authenticate_ class, and you may also provide the _password_instructions_ parameter to the _Authenticate_ class to provide instructions for the password when the user is using the _register_user_ or _reset_password_ widgets.
