### ISSUE TITLE
How to get password when user registers?

### ISSUE THREAD

**Issue by robinzimmermann** [mkhorasani/Streamlit-Authenticator#188]
Sorry to be slow... When I use the `authenticator.register_user()` widget I can fill in the form and submit it successfully:

```
(
    email_of_registered_user,
    username_of_registered_user,
    name_of_registered_user,
) = authenticator.register_user(pre_authorization=True)
```

I can get the email, username, and name. But how do I get the password that the user entered?

I can't find the answer in the doc. Maybe it's obvious, but I'm not seeing it. I am a bit new to python and streamlit, btw...

**Comment by mkhorasani** [comment]
Hi @robinzimmermann, as a safety precaution, the plain text password is deliberately not returned to the developer, it will be automatically hashed and saved into the config file without any records of its plain form in any way.

**Comment by robinzimmermann** [comment]
Thanks, @mkhorasani. But when I run the app locally in streamlit, or deploy it to the Streamlit Community Cloud, I don't see my `config.yaml` file changed when I register. Nor do I see my email addressed from the `pre-authorized:emails` section of `config.yaml`.

Is there something I could be doing wrong that's causing `config.yaml` not to be updated by the `Streamlit-Authenticator` library? Because otherwise it all works based on what's in `config.yaml - i.e., I can login. It's just that the file never gets updated at runtime.

**Comment by mkhorasani** [comment]
Please don't forget to implement [step 10](https://github.com/mkhorasani/Streamlit-Authenticator?tab=readme-ov-file#10-updating-the-configuration-file) of the readme file.

**Comment by robinzimmermann** [comment]
Darn, now I'm embarrassed, that was it!

Thank you so much, I was totally stuck until I got your hint!
