### ISSUE TITLE
Letting users register when deployed to Streamlit Community Cloud

### ISSUE THREAD

**Issue by robinzimmermann** [mkhorasani/Streamlit-Authenticator#189]
Sorry to ask another newbie question...

I am deployed to Streamlit Community Cloud. When a user registers, the `config.yaml` file doesn't get updated.

When deployed that way, am I supposed to use Streamlit secrets instead, as documented [here](https://docs.streamlit.io/streamlit-cloud/get-started/deploy-an-app/connect-to-data-sources/secrets-management)?

If so, then should I replace:

```
with open("config.yaml") as file:
    config = yaml.load(file, Loader=SafeLoader)
```

with code to read from secrets, and replace:

```
with open("config.yaml", "w") as file:
    yaml.dump(config, file, default_flow_style=False)
```

with code to save to secrets?

Or is there a different approach I'm supposed to use?

**Comment by mkhorasani** [comment]
No worries, yes I believe that will be fine.
