### ISSUE TITLE
multi-user management

### ISSUE THREAD

**Issue by ivan-schinella** [mkhorasani/Streamlit-Authenticator#191]
Hello, I've been using your library for a couple of months after evaluating a few other authentication systems. I haven't switched to your latest interesting version (callback, unrendered location, captcha) due to the reported bugs that I also encountered. However, I now find myself needing to implement an authentication mechanism for a web app that I plan to distribute, where each user can log in only once. Essentially, if "jsmith" is logged in on a PC/browser, he won't be able to log in from another PC/browser. Your library doesn't natively support this concurrent management, so I'm developing an internal solution using Supabase and the streamlit-cookies-controller library.

Do you have plans to integrate multi-user management in your roadmap?

Thanks for your efforts and for your work!

**Comment by mkhorasani** [comment]
Hey @ivan-schinella, thank you for reaching out. I will implement this feature in the next version which will be released within the next few weeks. Please stay tuned!

**Comment by ivan-schinella** [comment]
I'm very happy to read this. My personal solution works on a boilerplate web app used for prototyping, but if I want to apply it to my real (multi-page) app, I will need to rewrite many parts of the code. I'm really looking forward to trying your new version. Let me know if it's possible to send you a coffee 😉

**Comment by mkhorasani** [comment]
> I'm very happy to read this. My personal solution works on a boilerplate web app used for prototyping, but if I want to apply it to my real (multi-page) app, I will need to rewrite many parts of the code. I'm really looking forward to trying your new version. Let me know if it's possible to send you a coffee 😉

Sure will do!

**Comment by mkhorasani** [comment]
Hi @ivan-schinella, this feature is now implemented. You may provide the _single_session_ parameter to the _login_ and _experimental_guest_login_ widgets which limits each individual user to one session at a time.

**Comment by ivan-schinella** [comment]
Hi, I'm looking forward to trying out the new features of your component! Thanks!
