### ISSUE TITLE
Enhancement: Option to remove "Username" as a required field

### ISSUE THREAD

**Issue by brdemorin** [mkhorasani/Streamlit-Authenticator#194]
Not an issue but an enhancement -> option to remove username and use only email and password

**Comment by mkhorasani** [comment]
Hi @brdemorin, you can already implement such a feature. Just rename the username field to email using the `fields={'Username':'Email']` parameter for the login widget.

**Comment by brdemorin** [comment]
Thx for the response. I had planned to do just that, but when I try to eliminate the email field altogether and use the username field for that, I get errors.

                    fields={
                        'Form name': 'Register user',
                        'Email': 'Email', 
                        'Username': 'Username',
                        'Password': 'Password',
                        'Repeat password': 'Repeat password',
                        'Register': 'Register'
                    },
