### ISSUE TITLE
login set captcha=True,not input captcha,

### ISSUE THREAD

**Issue by bendchen** [mkhorasani/Streamlit-Authenticator#205]
when I use this :
authenticator.login(captcha=True)
but not input captcha,some error:

<img width="648" alt="image" src="https://github.com/user-attachments/assets/07548f45-3ff3-4cd7-8761-756395c72642">

May require friendly error message prompts instead of system error messages appearing.
thanks

**Comment by mkhorasani** [comment]
Hi @bendchen, sorry in the readme I meant to place the login widget in a try and except block solely for this purpose, but I forgot to. I recommend you place the entire login part within a try/except block.

**Comment by bendchen** [comment]
OK, this is my mistake, let me use a try/except Function.
