### ISSUE TITLE
Lacking documentation about how to use the new "roles" attribute for users

### ISSUE THREAD

**Issue by jcohensolal** [mkhorasani/Streamlit-Authenticator#216]
Hello,

I see there is a new "**roles**" attribute in the credentials file in version 0.4.1. I am interested in showing/hiding widgets or pages depending on the user role. But I cannot find any documentation about how to use the roles attribute, and looking at the source code, I'm not convinced it is actually used anywhere for the purposes I am interested in.

Would it be possible to update the README.md file to clearly explain what this attribute is for and how it should be used?

Thanks a lot.

**Comment by mkhorasani** [comment]
Hi @jcohensolal, thank you for reaching out. Apologies, yes perhaps I should elaborate on this and will do! But just to give you a quick overview, you can provide a list of `register_user` to the `login` and `experimental_guest_login` widgets, once the user registers or logs in via the guest login, this list will be appended to the credentials dict under their username and will be added to the session state which is accessbile via `st.session_state['roles]` when the user logs in. How you then use it is entirely upto you.
