### ISSUE TITLE
AttributeError: 'Hasher' object has no attribute 'generate'

### ISSUE THREAD

**Issue by AnubhavYadavBCA25** [mkhorasani/Streamlit-Authenticator#219]
I am working on my project, where I used streamlit-authenticator library. When I am using this in my system locally, it works fine and user are able to register into web app without any problem, but when I deployed my web app on streamlit cloud, it gives this error:
![Screenshot 2024-10-07 212039](https://github.com/user-attachments/assets/fe58c6cf-c428-4c71-93c2-13006aa25756)

All the dependencies are added and when I login with pre registered username and password still it work fine in deployed web app.

I am not able to fix this issue, anyone please help me to fix it...

**Comment by mkhorasani** [comment]
Hi @AnubhavYadavBCA25, please note that the `Hasher.generate` function has been replaced with the `Hasher.hash` function which takes a string (not a list anymore) and returns its hashed form as string.
