### ISSUE TITLE
login widget doesn't disappear after successful login

### ISSUE THREAD

**Issue by ai4ki** [mkhorasani/Streamlit-Authenticator#222]
Thanks a lot for this!
I have a minor issue: The login widget doesn't disappear after successful login; it only disappears once you interact with the app for the first time. I unelegantly solved this with an automatic st.rerun() but I'm wondering if I'm missing something. I simply use the example code, nothing else.

**Comment by mkhorasani** [comment]
Dear @ai4ki, thank you for reaching out. Please provide the config file as a path to the `Authenticate` class as follows:

```
authenticator = stauth.Authenticate('/config.yaml')
```

This will solve this problem and it will also eliminate the need for you to update the config, as it will automatically be updated.

**Comment by ai4ki** [comment]
Thanks @mkhorasani for your fast reply!
I tried your solution but it didn't work. Turns out the problem was the "expiry_days" param. I had set it to 0 and this casues the widget to remain visible after login. For value >0 it disappears as intended.
