### ISSUE TITLE
User not pre-authorized to register

### ISSUE THREAD

**Issue by ys-ccc** [mkhorasani/Streamlit-Authenticator#223]
I'm using the registration component and I get an error when I test it“User not pre-authorized to register”
I don't know how to solve this problem

this is my code ：

authenticator = stauth.Authenticate(
    config['credentials'],
    config['cookie']['name'],
    config['cookie']['key'],
    config['cookie']['expiry_days'],
    config['preauthorized']
)

try:
    email_of_registered_user, \
    username_of_registered_user, \
    name_of_registered_user = authenticator.register_user(
        domains = None,
    )

    if email_of_registered_user:
        st.success('用户注册成功')

       
        config['credentials']['usernames'][username_of_registered_user] = {
            'email': email_of_registered_user,
            'name': name_of_registered_user,
            'password': stauth.Hasher([st.session_state['password']]).generate()[0]  # 哈希密码
        }

        
        with open(yaml_file_path, 'w', encoding='utf-8') as file:
            yaml.dump(config, file, default_flow_style=False)

I also did the preparation in the yawl in this way

preauthorized:
  emails: []

**Comment by ys-ccc** [comment]
I delete pre-authorized from my code as you say and the error now are “Pre-authorization argument must not be None”
As I want no limit to user to register, why the code still check pre-authorized

**Comment by mkhorasani** [comment]
> I delete pre-authorized from my code as you say and the error now are “Pre-authorization argument must not be None” As I want no limit to user to register, why the code still check pre-authorized

I believe you are using an older version of Streamlit-Authenticator. Please update to the latest version.
