### ISSUE TITLE
st.set_page_config in multi page app -> StreamlitSetPageConfigMustBeFirstCommandError

### ISSUE THREAD

**Issue by mpreusse** [mkhorasani/Streamlit-Authenticator#224]
I built a Streamlit multi page ap where some pages use `st.set_page_config` to change the container width:

```
import streamlit as st

st.set_page_config(page_title="My title", layout="wide")
```

The app works without `streamlit-authenticator`. When I add authentication, I get an error for every page using `st.set_page_config`. When I remove `st.set_page_config` the page loads without error but the container width is back to default of course.

Any idea how `streamlit-authenticator` interferes with `st.set_page_config`?

### Error

```
StreamlitSetPageConfigMustBeFirstCommandError: set_page_config() can only
 be called once per app page, and must be called as the first Streamlit command in your script.
```
<img width="740" alt="Bildschirmfoto 2024-10-10 um 11 31 01" src="https://github.com/user-attachments/assets/2dc3a01e-9309-42b0-90a6-009d5adf7e8d">

**Comment by mkhorasani** [comment]
Hi @mpreusse, I don't use the `st.set_page_config` anywhere in Streamlit-Authenticator, however, try setting your page config before you import and setup Streamlit-Authenticator, perhaps that would fix this problem.

**Comment by mpreusse** [comment]
Thanks for your quick reply @mkhorasani! Unfortunately, the problem persists.

I import and setup Streamlit-Authenticator in the main file and `st.set_page_config` is used on the individual pages. When I add a `st.set_page_config` on the main file before importing Streamlit-Authenticator I still get the error on the individual pages.

There is no point to using `st.set_page_config` in the main file anyways, so it's kind of impossible to run it before importing Streamlit-Authenticator 😄

**Comment by dtiosd** [comment]
You need to write the set_page_config at the top, you can refer to my code, and I avoided this bug this way


```python
import streamlit as st
import streamlit_authenticator as stauth
import yaml
from yaml.loader import SafeLoader

# 添加 st.set_page_config
st.set_page_config(
    page_title="Your App Title",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Loading config file
with open('config.yaml', 'r', encoding='utf-8') as file:
    config = yaml.load(file, Loader=SafeLoader)

# Creating the authenticator object
authenticator = stauth.Authenticate(
    config['credentials'],
    config['cookie']['name'],
    config['cookie']['key'],
    config['cookie']['expiry_days']
)

def login():
    try:
        authenticator.login()
    except Exception as e:
        pass

def logout():
    authenticator.logout()

login_page = st.Page(login, title="登录", icon=":material/login:")
logout_page = st.Page(logout, title="登出", icon=":material/logout:")

dashboard = st.Page(
    "reports/dashboard.py", title="仪表板", icon=":material/dashboard:", default=True
)
bugs = st.Page("reports/bugs.py", title="错误报告", icon=":material/bug_report:")
alerts = st.Page(
    "reports/alerts.py", title="系统警报", icon=":material/notification_important:"
)

search = st.Page("tools/search.py", title="搜索", icon=":material/search:")
history = st.Page("tools/history.py", title="历史记录", icon=":material/history:")



if st.session_state["authentication_status"]:
    pg = st.navigation(
        {
            "账户": [logout_page],
            "报告": [dashboard, bugs, alerts],
            "工具": [search, history],
        }
    )
else:
    pg = st.navigation([login_page])

pg.run()
```

**Comment by mpreusse** [comment]
Thanks for the code snipper @dtiosd! Yes, you can set the page config on the main page. 

The issue is that you can't set the page config on the _other_ pages.
