### ISSUE TITLE
How to rewrite a login page

### ISSUE THREAD

**Issue by dtiosd** [mkhorasani/Streamlit-Authenticator#231]
I want to rewrite the style of the login page and add some verification methods, how can I rewrite and customize the login page I want with the same functionality as the source code?

**Comment by mkhorasani** [comment]
Hi @dtiosd, I'm sorry but currently Streamlit-Authenticator provides limited customizability with the `fields` parameter that allows you to customize the names of each field. Other than that no other provisions have been made or are being planned to enable greater customizability.
