### ISSUE TITLE
issues when connecting to login endpoint

### ISSUE THREAD

**Issue by HayatoSempai** [mkhorasani/Streamlit-Authenticator#232]
Hello,

I have implemented a repository with a postgre database where my users are stored.
I want to access my endpoint that gives me an authentication token with 

```
api_url = "http://backend:8000/login/access-token"

# Create Authenticator instance
authenticator = Authenticator(
    url=api_url,
    headers={"Content-Type": "application/x-www-form-urlencoded"},
    method="post",
    token_key="access_token",
    cookie_lifetime=timedelta(hours=300)
)
authenticator.login()
```

It does work but I have 2 issues : 
- cookie_lifetime is unconsistent : if I change to minutes or hours the duration does not change (I have the same duration for seconds=30 and hours=30) It only changes with the value after the equal.
- authenticator.logout() does not work and my application still run as I was still logout until the cookie_lifetime is passed

Thx for reading and I hope you can help

**Comment by mkhorasani** [comment]
Dear @HayatoSempai, none of the arguments you are invoking for the `Authenticate` object exist in Streamlit-Authenticator. Please follow the examples provided in the [readme](https://github.com/mkhorasani/Streamlit-Authenticator?tab=readme-ov-file#4-setup). I can only provide help for use cases that are within the scope of this package. Thank you.
