### ISSUE TITLE
config.yml not populating new user details after sign up via Google 

### ISSUE THREAD

**Issue by iamsharduld** [mkhorasani/Streamlit-Authenticator#236]
config.yml not populating new user details after sign up via Google, so throws below error after every restart

`raise LoginError('User not authorized')
streamlit_authenticator.utilities.exceptions.LoginError: User not authorized`

**Comment by mkhorasani** [comment]
Please make sure you are saving the config file as shown in [this](https://github.com/mkhorasani/Streamlit-Authenticator?tab=readme-ov-file#13-updating-the-config-file)step.

**Comment by iamsharduld** [comment]
Thank you!

**Comment by vrolok** [comment]
Sorry for hijacking this thread. I'm experiencing a similar issue with the `microsoft` provider for `experimental_guest_login`, where I can authenticate initially but get a 'User not authorized' error after reloading the page. I've attempted to save the config file, but no changes are persisted after logging in.
