### ISSUE TITLE
using exact documentation, i can login rbriggs, but i cant login jsmith

### ISSUE THREAD

**Issue by rhavif-budiman** [mkhorasani/Streamlit-Authenticator#239]
hi, i try your code and your exact documentation, but why  i can login "rbriggs" with his password "def", but i cant login jsmith with password "abc"? also you can update your documentation in installation section, add -> from streamlit_authenticator.utilities import (CredentialsError, ForgotError,Hasher,LoginError,RegisterError,ResetError,UpdateError,)

**Comment by rhavif-budiman** [comment]
![image](https://github.com/user-attachments/assets/d5d22920-ee65-4e73-ae22-410b6036acf4)
this is image i cant login with jsmith

**Comment by mkhorasani** [comment]
Can you please share make sure that all the passwords in your config file are hashed?

**Comment by rhavif-budiman** [comment]
so im using your documentation config
![image](https://github.com/user-attachments/assets/b25fc74a-a6f8-4a09-b08e-21acbca47e05)

**Comment by mkhorasani** [comment]
> so im using your documentation config ![image](https://private-user-images.githubusercontent.com/143685548/381119564-b25fc74a-a6f8-4a09-b08e-21acbca47e05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMDUxNzQsIm5iZiI6MTczMDIwNDg3NCwicGF0aCI6Ii8xNDM2ODU1NDgvMzgxMTE5NTY0LWIyNWZjNzRhLWE2ZjgtNGEwOS1iMDhlLTIxYWNiY2E0N2UwNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOVQxMjI3NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MGUzYmM4ZjQxMjhkZmZkZjgyYmNjODQzZWIzYjU1MWViNDI2NmViNzM2ZmQ1M2ZlZTIyNGYyM2UzZjBjN2MxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.hGzUhnw6EXnX8JvX_PXRr8o92X8KDMReTFjHUyVDaCA)

Are you re-saving the config file as shown [here](https://github.com/mkhorasani/Streamlit-Authenticator?tab=readme-ov-file#13-updating-the-config-file)?

**Comment by rhavif-budiman** [comment]
yeah, im saving it

**Comment by rhavif-budiman** [comment]
but its weird, jsmith failed to login but brigs can login

**Comment by mkhorasani** [comment]
> yeah, im saving it

When you update it, are the plain-text passwords being hashed? The passwords should look something like this after being hashed: `$2b$12$E9/bCaN/r8sN/FV2l8NpgOgspUBAp7UAVU6BgsXJzp/pW8gQWCprC`

**Comment by rhavif-budiman** [comment]
![image](https://github.com/user-attachments/assets/8b356e60-bf3e-43b4-af23-6596f21c0c9d)
so this is my code, i only copy and paste based on your documentation, based on your documentation, its auto hashed right?
or should the step hash the password, update yaml with hashed value using , and saving the config file?

**Comment by mkhorasani** [comment]
> ![image](https://private-user-images.githubusercontent.com/143685548/381129939-8b356e60-bf3e-43b4-af23-6596f21c0c9d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMDcwODMsIm5iZiI6MTczMDIwNjc4MywicGF0aCI6Ii8xNDM2ODU1NDgvMzgxMTI5OTM5LThiMzU2ZTYwLWJmM2UtNDNiNC1hZjIzLTY1OTZmMjFjMGM5ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOVQxMjU5NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NjRmMDUyNWJkZWZhNmRiNjI0MTlkOGQ5YmJmNTM5ZTk0ZDZkOWNmMDdiM2ZjNThjMDFlMmFhMWI5NjVjYzkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.EAzZs66s1f6TZP44na0ooBkWfXmdoMUaYE3nfkw0rRQ) so this is my code, i only copy and paste based on your documentation, based on your documentation, its auto hashed right? or should the step hash the password, update yaml with hashed value using , and saving the config file?

By default passwords will be auto-hashed unless you disable it. If auto-hash is set to True, which is the case for you, then the first time you run your app, all the plain text passwords should be automatically hashed and re-saved to the config file, if you can still see plain text passwords in the config file, then it means that for whatever reason you're not able to update the config file. Alternatively, you can provide the config file as a path to the Authenticate class as shown below:

```
    authenticator = Authenticate(
        '../config.yaml'
    )
```

This way the config file will be automatically updated. Try it and let me know what happens.

**Comment by rhavif-budiman** [comment]
![image](https://github.com/user-attachments/assets/1a65478e-dd2c-47a7-a5c9-0df96b7f7837)
so im using 
`    authenticator = Authenticate(
        '../config.yaml'
    )`
    
    in my code, but still the error i can login with rbriggs, and i cant jsmith or any added username 
    
    and the yaml not updated

**Comment by rhavif-budiman** [comment]
ok, now i know what is the problem, its config path!!!, actually its my bad because not thorough when see your code, on your documentation its "../config" and it will move the config outside my folder current, also i see another problem, on config especcially on password it cant use number, it must string, ahahaha
 thanks a lot , your code really help many people, i hope you success in future
