### ISSUE TITLE
Using Streamlit Authenticator with secrets.toml file 

### ISSUE THREAD

**Issue by tylncck** [mkhorasani/Streamlit-Authenticator#242]
Hello, I'm new to this Streamlit Authenticator package and appreciate all the effort put into developing it. After successfully implementing my app's login and logout functions, I'm currently working on the reset password and user information parts. My app is deployed to Streamlit Community Cloud and I'm using secret.toml file in my local repo and streamlit secrets in the cloud. As far as I understand, the reset password and update user information widgets works with a config.yaml file. I wonder how I can use these features with secret.toml file or alternatively (if I use the config.yaml file) how I can save the content of yaml file to streamlit secrets in Community Cloud. 
Once again, thanks for this awesome package and thanks in advance for the answers.

**Comment by mkhorasani** [comment]
Hey @tylncck thank you for reaching out. Sorry I was too lazy to write up a solution myself, so I asked and ChatGPT and will share the answer below:

```
To convert your config.yaml (used with Streamlit Authenticator) to a Streamlit secrets secrets.toml file, you'll need to follow these steps:

Step 1: Structure of config.yaml
Suppose your config.yaml file looks like this:

yaml
Copy code
credentials:
  usernames:
    johndoe:
      email: johndoe@example.com
      name: John Doe
      password: $2b$12$K6UO3GJXzIXfGhf.1JH5xuob/sZb7C5kPoJW5GV/uow/XksbOmNke

cookie:
  expiry_days: 30
  key: some_random_secret_key
  name: my_cookie

preauthorized:
  emails:
    - jane@example.com
    - alice@example.com
Step 2: Convert to secrets.toml
In Streamlit Cloud, you can store your secrets in a secrets.toml file. Here's how you can convert the above config.yaml into the secrets.toml format:

toml
Copy code
[credentials.usernames.johndoe]
email = "johndoe@example.com"
name = "John Doe"
password = "$2b$12$K6UO3GJXzIXfGhf.1JH5xuob/sZb7C5kPoJW5GV/uow/XksbOmNke"

[cookie]
expiry_days = 30
key = "some_random_secret_key"
name = "my_cookie"

[preauthorized]
emails = ["jane@example.com", "alice@example.com"]
Step 3: Accessing Secrets in Your Streamlit Code
Once you've added this data to your secrets.toml, you can access the values using st.secrets in your Streamlit app:

python
Copy code
import streamlit as st
import streamlit_authenticator as stauth

# Load credentials
credentials = st.secrets["credentials"]
cookie = st.secrets["cookie"]
preauthorized = st.secrets["preauthorized"]

# Initialize authenticator
authenticator = stauth.Authenticate(
    credentials,
    cookie["name"],
    cookie["key"],
    cookie["expiry_days"],
    preauthorized["emails"]
)

name, authentication_status, username = authenticator.login("Login", "main")

if authentication_status:
    st.success(f"Welcome {name}!")
elif authentication_status is False:
    st.error("Username or password is incorrect")
else:
    st.warning("Please enter your username and password")
```

Hope this helps!

**Comment by mkhorasani** [comment]
Hi @tylncck, thank you for reaching out, but currently there is no way to programmatically write to Streamlit secrets when deployed on cloud. I recommend you use a database as shown in [this](https://www.youtube.com/watch?v=eCbH2nPL9sU&t=191s) video.
