### ISSUE TITLE
option to disable hashing

### ISSUE THREAD

**Issue by batmanscode** [mkhorasani/Streamlit-Authenticator#25]
Hi, thanks for creating this component! I find the cookie authentication very useful.

I am storing the config as a streamlit secret so it is not necessary to hash the passwords. Is it possible to disable this? Right now I am getting an `invalid salt` error when I try to use plain text passwords.

**Comment by mkhorasani** [comment]
Hi @batmanscode, I'm glad that you find it to be helpful. As a rule of thumb passwords should NEVER be unhashed. It is simply far too risky not to hash them. Consequently, I never even contemplated enabling such a feature, however, if you really want to, you can do so by modifying the source code - that particular feature is implemented in the authenticate.py script. Cheers.

**Comment by batmanscode** [comment]
> Hi @batmanscode, I'm glad that you find it to be helpful. As a rule of thumb passwords should NEVER be unhashed. It is simply far too risky not to hash them. Consequently, I never even contemplated enabling such a feature, however, if you really want to, you can do so by modifying the source code - that particular feature is implemented in the authenticate.py script. Cheers.

Thank you. I was wondering since they will be stored as environment variables and not a database
