### ISSUE TITLE
Extra-Streamlit-Components breaks Authenticator?

### ISSUE THREAD

**Issue by ceefar** [mkhorasani/Streamlit-Authenticator#26]
Had installed authenticator, everything set up and working fine, then decided to install extra components to take a look and now login for throws this error over and over. "Invalid Salt""

The only other things I can think that may have caused this was wiping the cache, but pretty confident I had done that already with no issues.

Any ideas for a fix?

**Comment by ceefar** [comment]
Ive tried new folder with new venv reinstalling packages, uninstalling packages, same problem :(

**Comment by mkhorasani** [comment]
Dear @ceefar, please try clearing your browser's cookies related this your application and try again.
