### ISSUE TITLE
What's the recommended way to store login info as secrets?

### ISSUE THREAD

**Issue by batmanscode** [mkhorasani/Streamlit-Authenticator#27]
Using a yaml>toml converter it's possible to store the entire yaml configuration as a secret using streamlit cloud, which works as expected.

For deploying from other services, how can leverage environment variables?

**Comment by mkhorasani** [comment]
Dear @batmanscode, if you are deploying on Streamlit Cloud (Streamlit's own servers) they have their own implementation of environment secrets which you may read more about [here](https://docs.streamlit.io/streamlit-cloud/get-started/deploy-an-app/connect-to-data-sources/secrets-management). If you are deploying on other servers such as Heroku, each platform may have its own way of storing secrets which you will have to enquire about separately. Hope this helps.

**Comment by batmanscode** [comment]
Thanks @mkhorasani . As I said it was easy to store the whole yaml as a secret in Streamlit cloud

For heroku if I wanted to save part of the yaml file as a secret I found this library: https://github.com/mkaranasou/pyaml_env
