### ISSUE TITLE
Logout requires two presses

### ISSUE THREAD

**Issue by ted-dunstone** [mkhorasani/Streamlit-Authenticator#3]
When using the log out button it always seems to require at least two presses to fully logout back to the login screen.

**Comment by mkhorasani** [comment]
Hi, I believe this is due to the Cookie manager that is attempting to delete the reauthentication cookie. I will try to fix this issue by adding the option of not using cookies in the future, until the issue with the cookies is resolved. Thanks.

**Comment by ted-dunstone** [comment]
That sounds great. Could it be supported by putting the token on the url perhaps?

Thanks for making a much needed component.


Ted Dunstone
Biometix Pty Ltd

E: ***@***.******@***.***>
T: +61 (0) 419 990 968 (Aus) +65 8363 8225 (Sing)
W: www.biometix.com<http://www.biometix.com/>
A: Unit 12, 11 National Circuit, Barton, 2600, ACT


________________________________

**Comment by mkhorasani** [comment]
A persistent way is required to store the contents of the reauthentication string, so I'm not sure how that would work with a URL token, asides from the fact that it probably won't be as secure. You're most welcome!

**Comment by AchimTack** [comment]
@mkhorasani Thanks for having a look at it as I ran into the same issue. Would be great to have it fixed as the authenticator is super-helpful!

**Comment by mkhorasani** [comment]
Hey, @AchimTack have you tried updating extra-streamlit-components to the latest version?

**Comment by AchimTack** [comment]
Thanks @mkhorasani for your quick response! I just updated the extra-streamlit-components to 0.1.53 . 
Aside from that I set the cookie_expiry_days to 0 in the authenticator and it works fine now.

**Comment by mkhorasani** [comment]
Dear all, please install the latest version of [Streamlit-Authenticator v0.1.1](https://pypi.org/project/streamlit-authenticator/0.1.1/), as this issue has been resolved. Thank you for your patience.
