### ISSUE TITLE
Streamlit-Authenticator - Transition from login page to main page is rough

### ISSUE THREAD

**Issue by anujwwt** [mkhorasani/Streamlit-Authenticator#32]
Hi Mohamed - the transition from login page to main page for our app is very rough. i see login page for few seconds overlayed with main page which decreases the user experience. can you rectify the issue please.

**Comment by mkhorasani** [comment]
Hi @anujwwt, this is a known issue related to reading the reauthentication cookie. Once a solution has been found a release will be made. Regards.

**Comment by roliii** [comment]
> Hi @anujwwt, this is a known issue related to reading the reauthentication cookie. Once a solution has been found a release will be made. Regards.

I am really waiting for a solution to this problem.

**Comment by VovaViliLox** [comment]
Here is the way I bypassed this in my Streamlit app:

1) Put the login tab inside st.empty() placeholder

2) Upon successful login, clear the placeholder

3) [To bypass a bug with clearing st.empty](https://playground.streamlit.app/?q=empty-doesnt-work), sleep of 0.01 seconds.

**Comment by mkhorasani** [comment]
Dear all please check the latest release [v0.3.2](https://github.com/mkhorasani/Streamlit-Authenticator/releases/tag/v0.3.2).
