### ISSUE TITLE
Return user email, Name for new user

### ISSUE THREAD

**Issue by psyrixen** [mkhorasani/Streamlit-Authenticator#35]
Hi,
Is there a way that we can get the email address and the name of the newly registered user without modifying the package code. Currently is returns if a new user has successfully created account or not.

**Comment by mkhorasani** [comment]
Hi @psyrixen, this is an excellent point. I will try to implement it in a future release. In the meantime, feel free to edit line 347 of authenticate.py to enable this feature. Should be relatively straight forward. Cheers.

**Comment by psyrixen** [comment]
Hi,

Thanks for the quick answer. Also, can you please also include the option to clear the forms after submission. I know its just a small addition but will improve the behavior of the component vastly. Currently the forms don't clear after the form is submitted.

Much thanks again for this awesome component. Really appreciate it!

Have a good day

**Comment by mkhorasani** [comment]
@psyrixen sure will do that too. Stay posted!

**Comment by mkhorasani** [comment]
Hi @psyrixen, this feature has been implemented in release [v0.2.4](https://github.com/mkhorasani/Streamlit-Authenticator/releases/tag/v0.2.4). The **register_user** widget now return all these values.
