### ISSUE TITLE
Can I block a new login, when a user is already logged in?

### ISSUE THREAD

**Issue by alicjagrocholska** [mkhorasani/Streamlit-Authenticator#40]
Hello, I have a streamlit webapp that uses streamlit-authenticator and it works just fine, but we have seen some 'collisions' when two users are logged in a the same time (same variable names, different values, erase each other temporary files, and so on). Is there a way to block the new login to be sure that only one user can login at the same time?

**Comment by mkhorasani** [comment]
Hi, are the users logged in at the same time on the same device? Or they are logged in on different devices?

**Comment by alicjagrocholska** [comment]
They are logged in different devices, and sometimes working with the same files and the same variables names (but different values/dates, for example one could be doing a weekly report and the other a montly report of the same thing).

**Comment by mkhorasani** [comment]
I see. Well, I can definitely implement a feature that would disallow a second user from logging in with the same credentials while another user is already logged in. I will leave this issue open until I address this issue in a future release. Thank you for pointing this issue out!

**Comment by mabusdogma** [comment]
+1!
I'm looking forward for this implementation too!

**Comment by evofromko** [comment]
Oh yes, i was looking into this as well, i think a lot of us would be happy if this option is available.

**Comment by mkhorasani** [comment]
Hi @alicjagrocholska, this feature has been implemented in release [v0.2.4](https://github.com/mkhorasani/Streamlit-Authenticator/releases/tag/v0.2.4). You can now pass a **max_concurrent_users** number to the **login** widget to limit that maximum number of users logged in at the same time.
