### ISSUE TITLE
Not able to create a new account using register_user

### ISSUE THREAD

**Issue by poojanaik08** [mkhorasani/Streamlit-Authenticator#41]
I am new to streamlit. I want to have a login and signup functionality in my application. I am able to successfully implement login using the username and password stored in the config.yaml file. However, I am not able to properly implement the register_user or reset/update the password. The program runs smoothly and I get the 'registration successful' message but when I try to log in using the new credentials I get the 'incorrect username/password' error.

![image](https://user-images.githubusercontent.com/70855999/207382373-15851996-ee0a-4b32-84f0-846437d01cd5.png)

![image](https://user-images.githubusercontent.com/70855999/207382716-d6a75a55-cbe3-4ad1-ad9c-61c30ea17e2d.png)

**Comment by mkhorasani** [comment]
Please ensure you are resaving the newly registered credentials in the config file as shown below:

```
with open('../config.yaml', 'w') as file:
    yaml.dump(config, file, default_flow_style=False)
