### ISSUE TITLE
Feature - Only allow users within a certain domain to create an account

### ISSUE THREAD

**Issue by abdulrabbani00** [mkhorasani/Streamlit-Authenticator#43]
Small lift here. But it would be great if we could define who can create a user account. This would allow users to make a streamlit application public, and then allow everyone from their organization to create individual accounts.

Also happy to integrate this if you are willing to accept it :D

**Comment by mkhorasani** [comment]
Hi @abdulrabbani00, thank you for the efforts, please give me some time to peruse these features before making any merges. Thank you!

**Comment by elcronos** [comment]
I think this would be great

**Comment by abdulrabbani00** [comment]
There is a PR open for this - https://github.com/mkhorasani/Streamlit-Authenticator/pull/44

Feel free to use my fork for this functionality today and a faster startup

**Comment by mkhorasani** [comment]
Hi all, this feature has been implemented in release [v0.2.4](https://github.com/mkhorasani/Streamlit-Authenticator/releases/tag/v0.2.4). You can now pass a **domains** list to the **register_user** widget that specifies the permissible domains that an email must belong to.
