### ISSUE TITLE
Feature - Disallow registration if email is already taken.

### ISSUE THREAD

**Issue by NoNeuronsNoStress** [mkhorasani/Streamlit-Authenticator#46]
Currently the registration only blocks registration if the username is already taken, but it allows to register with the same email infinite time, which is not good. 
Perhaps you could add a feature that doesnt allow to use the same email more than once.

**Comment by mkhorasani** [comment]
Hi @NoNeuronsNoStress, yes I guess that makes sense. Will implement it in a future release.

**Comment by mkhorasani** [comment]
Hi @NoNeuronsNoStress , this feature has been implemented in release [v0.2.4](https://github.com/mkhorasani/Streamlit-Authenticator/releases/tag/v0.2.4).
