### ISSUE TITLE
Request for help

### ISSUE THREAD

**Issue by satishgc227** [mkhorasani/Streamlit-Authenticator#47]
Respected sir,
            Kindly help me how to increase the size of message input box to 1 GB from 1MB. I am able to do it for file uploader, but not for message input box.

Regards,
Satish

**Comment by mkhorasani** [comment]
Dear @satishgc227, this is something that is outside of my scope, please contact Streamlit directly on their forums to find a solution to this problem. Regards.

**Comment by satishgc227** [comment]
Sir plz give me the link where i can contact them.

**Comment by mkhorasani** [comment]
https://discuss.streamlit.io/

**Comment by mkhorasani** [comment]
https://discuss.streamlit.io/

**Comment by satishgc227** [comment]
Sir i a not able to find where i can ask questions.There is no clear
description about this.

**Comment by mkhorasani** [comment]
Click on the 'New Topic' button on the upper right of the platform to ask your question.
