### ISSUE TITLE
importing the Authenticator Package gives an error

### ISSUE THREAD

**Issue by mthandenisithole** [mkhorasani/Streamlit-Authenticator#48]
Hi, 
When I try to **import streamlit_authenticator as stauth** I get  this  error message:

  Import "streamlit_authenticator" could not be resolvedPylance[reportMissingImports](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportMissingImports)

Please help, is the package still working?

**Comment by mkhorasani** [comment]
Hi @mthandenisithole, yes the package is as it was. Please try to create a new environment and reinstall streamlit_authenticator to see if the problem persists.

**Comment by mthandenisithole** [comment]
Thanks a lot it worked.

**Comment by mthandenisithole** [comment]
Can you please help with the Authenticate arguments, how should the parameter passed to credentials argument look like if for example I have 2 users? 

authenticator = stauth.Authenticate(credentials= users, cookie_name= "xyz", key="abcd")

name,authentication_status, username = authenticator.login("Login","main")

Because I am getting an error that __init__
    self.credentials['usernames'] = {key.lower(): value for key, value in credentials['usernames'].items()}
                                                                          ~~~~~~~~~~~^^^^^^^^^^^^^
TypeError: list indices must be integers or slices, not str


Also the cookie name & key can be anything right?

**Comment by mkhorasani** [comment]
If you are using streamlit_authenticator==0.2.1, please provide credentials and other parameters in the form of [this config file.](https://github.com/mkhorasani/Streamlit-Authenticator/blob/main/config.yaml)

**Comment by mthandenisithole** [comment]
Thanks a lot.
What if I would to store the credentials in a SQL database instead of yaml file, how can go about this?
So that when users Login the credentials for authentication are pulled directly from the database

**Comment by mkhorasani** [comment]
You're welcome. And yes there is a way to connect it to a database, for more information please refer to [this ](https://www.youtube.com/watch?v=eCbH2nPL9sU) tutorial.
