### ISSUE TITLE
Clean up README.md

### ISSUE THREAD

**Issue by fascani** [mkhorasani/Streamlit-Authenticator#51]
Some possible corrections:

1. Say somewhere one needs to install pyyaml and import yaml
2. In the first code snippet in 'Creating a login widget', replace `Loader=SafeLoader` by `Loader=yaml.SafeLoader` 

Or something like that as I struggled to realize the above from the README.md. It may be obvious to a lot of folks but it was not to me.

I could do it myself but I am hesitant as I don't want to interfere in your README. Package is great by the way! Thanks!

**Comment by mkhorasani** [comment]
Hey @fascani, that's an excellent point, I have modified point 2 in the readme file to reflect this. Cheers!
