### ISSUE TITLE
KeyError: 'st.session_state has no key "$$GENERATED_WIDGET_ID-708114cdb90d1a7f715f08aeb5ed8572-None".

### ISSUE THREAD

**Issue by ryanshrott** [mkhorasani/Streamlit-Authenticator#56]
Randomly getting this error from time to time. How to fix it?
KeyError: 'st.session_state has no key "$$GENERATED_WIDGET_ID-708114cdb90d1a7f715f08aeb5ed8572-None". Did you forget to initialize it? More info: https://docs.streamlit.io/library/advanced-features/session-state#initialization'
2023-04-01 21:19:26.431 API queries_quota: 60

**Comment by mkhorasani** [comment]
Hi @ryanshrott, I am not sure if this error is related to streamlit-authenticator, please refer to [this](https://discuss.streamlit.io/t/keyerror-st-session-state-has-no-key-generated-widget-id-none-did-you-forget-to-initialize-it-more-info/39325) article for the latest updates.

**Comment by vidz1979** [comment]
Hi @mkhorasani !! 

I've added some info's in that thread. I think that has something to do with authenticator.

https://discuss.streamlit.io/t/keyerror-st-session-state-has-no-key-generated-widget-id-none-did-you-forget-to-initialize-it-more-info/39325/18?u=vidz1979

**Comment by mkhorasani** [comment]
Hi @vidz1979, as I am unable to recreate this error locally, can you please try to comment the [authenticate.py](https://github.com/mkhorasani/Streamlit-Authenticator/blob/main/streamlit_authenticator/authenticate.py) script to try to localize the exact line where this error is thrown?
