### ISSUE TITLE
[HowTo] Can it be integrated with Okta ODIC or SAML auth protocol?

### ISSUE THREAD

**Issue by vbabaria** [mkhorasani/Streamlit-Authenticator#6]
Looks like a great library.
is it possible to use Streamlit-Authenticator with [Okta](https://www.okta.com/products/authentication/)?

Thanks

**Comment by mkhorasani** [comment]
Glad you like it. I'm not personally familiar with Okta, but since it has a Python SDK it means that most likely it can be integrated. Feel free to try it out for yourself.

**Comment by mkhorasani** [comment]
Glad you like it. I'm not personally familiar with Okta, but since it has a Python SDK it means that most likely it can be integrated. Feel free to try it out for yourself.
