### ISSUE TITLE
Adding groups when registering users

### ISSUE THREAD

**Issue by Feromond** [mkhorasani/Streamlit-Authenticator#62]
I am a big fan of this current library and how simple it has made creating authentication within streamlit. One thing I am hoping that could be added is a group value for each user. I tested this implementation by modifying the library code directly for my project but I would hope there could be a true implementation created in the future. 

I have attached a screenshot with the modified function to implement a simple base version. Here a group parameter is created with the value set to "default" representing a default group. From here, I can manage and modify group permissions in my code easily. I would love for this change to be implemented so upon user registration I can already have a default group preset onto each user, and then it is possible to make future modifications easily, even if this library did not directly support changes such as that. 

I made this implementation on my personal project and then was able to control all permissions and assignment of different groups completely separate. This would just be a nice way to open the door for further access control within the app.

<img width="845" alt="modified_function" src="https://user-images.githubusercontent.com/53460081/235194870-451d7f19-858e-4f2f-bcf1-f9534e3c9011.png">

I love the project, thanks for your contribution to open source!

**Comment by mkhorasani** [comment]
Hey @Feromond, thank you for reaching out with this idea. Please feel free to share your implementation/source code, perhaps you could further develop this and make a pull request? Cheers!

**Comment by Feromond** [comment]
Okay sounds good. I will work on this and create a pull request in the near future. Thanks!
