### ISSUE TITLE
Consider changing cookie_expiry_days to cookie_expiry_secs?

### ISSUE THREAD

**Issue by voidel** [mkhorasani/Streamlit-Authenticator#67]
So that we may define smaller time ranges for expiry, i.e. 5 minutes.

Timestamp in the JWT supports seconds granularity but the current param defines expiry in days.

Furthermore the type of the days expiry is integer, which prevents us from achieving the same goal with a decimal.

**Comment by mkhorasani** [comment]
Hi @voidel, the function annotation requires the expiry days parameter to be an integer, but that is non-binding and you can in fact input the expiry days as a float. Thanks.
