### ISSUE TITLE
stauth.Hasher fail in 0.1.2

### ISSUE THREAD

**Issue by litonchen** [mkhorasani/Streamlit-Authenticator#7]
Hey, for the latest version 0.1.2, Hasher is no long existing.
0.1.1 can work

**Comment by mkhorasani** [comment]
The classes in this package were upper-cased in this release, i.e. stauth.hasher became stauth.Hasher, please ensure that you have modified your code accordingly.

**Comment by ronidee** [comment]
In version 0.3.2 it's `stauth.utilities.hasher.Hasher` in case anyone else is searching for it too.

(Note: [this](https://blog.streamlit.io/streamlit-authenticator-part-1-adding-an-authentication-component-to-your-app/) is out of date
