### ISSUE TITLE
st.session_state adding key without a value

### ISSUE THREAD

**Issue by manishb27** [mkhorasani/Streamlit-Authenticator#73]
After a while there is an error occurs. Follwing is the is error name. 

KeyError: 'st.session_state has no key "$$WIDGET_ID-066388677307bd58b4f92f728cc0bb22-text". Did you forget to initialize it? More info: https://docs.streamlit.io/library/advanced-features/session-state#initialization'

**Comment by ikanberjalandidarat** [comment]
Hi, I also have the same issue, the st.session_state does not load any value when using the authenticator.  
This is a quite recent issue, any ideas? @mkhorasani

**Comment by mkhorasani** [comment]
Hi @manishb27, @ikanberjalandidarat this is a rather perplexing issue that we cannot diagnose yet. As soon as I figure out what is happening I will inform everyone. Thank you for your pateince.

**Comment by SBVR-jeremy** [comment]
Hi @mkhorasani , I got the same issue. You can find similar and more detailled informations here : https://discuss.streamlit.io/t/keyerror-st-session-state-has-no-key-generated-widget-id-none-did-you-forget-to-initialize-it-more-info/39325/6

**Comment by daimoriwaki** [comment]
I got same issue. But after a long exploring I found the error did not come from authenticator but from other part of my code. In my case I set wrong API KEY for request, but received "widget brabra...". I strongly recommend dig other part of your code rather than digging authenticator. gl.
