### ISSUE TITLE
Use the email registered as a username

### ISSUE THREAD

**Issue by Persevera-Asset-Management** [mkhorasani/Streamlit-Authenticator#74]
Hi, I was wondering if it's possible to use only the email registered, instead of a username.

The complexity for the user increases, in a way that he or she has to remember two credentials.

Thank you!

Awesome library!

**Comment by mkhorasani** [comment]
Hi @Persevera-Asset-Management, thank you for reaching out. The user will only need his/her username and password when logging in, not email. The email is stored in case the user and admin want to reset the password and need to send the updated credentials to the user securely via email. Cheers.

**Comment by Persevera-Asset-Management** [comment]
Thank you, @mkhorasani!

I think I could not make myself clear, apologies.

What I meant is if it's possible to only use the email for user credentials.
It would be better if the user could register only using the e-mail, name (perhaps) and password.

In today's framework, the user has to input: name, username and email.

By the way, I'm using the email for the "forget my password" as well!

**Comment by mkhorasani** [comment]
Oh I see, well in that case I will see if I can implement this in a future release. Thank you.

**Comment by Persevera-Asset-Management** [comment]
Thank you!

It would be awesome! 

Is it difficult to implement?

Cheers and one more time, thank you for the library and quick answer.
