### ISSUE TITLE
Question: where I can find new password after I clicked "forgot_password"

### ISSUE THREAD

**Issue by yuxuan7z** [mkhorasani/Streamlit-Authenticator#75]
Hi,

Thank you for creating this powerful Authenticator tool. I have a question about 'Forgot password' widget. After I submitted my forgot password request by username, where I can find the new generated random password? I did not receive an email to my account about new password information. The config.yaml file's password is hashed and how I suppose to get the new random password from my yaml file? Thank you very much for your help.

**Comment by mkhorasani** [comment]
Hi @yuxuan7z, thank you for reaching out. Please note that this widget does not automatically email the user their new random password. Instead it returns the new random password as a string and you will then have to develop your own code to send it to them in any way that you require. For further information please refer to [point number 6](https://github.com/mkhorasani/Streamlit-Authenticator/tree/main#6-creating-a-forgot-password-widget) in the readme file.

**Comment by yuxuan7z** [comment]
Hi @mkhorasani, thank you very much for your quick answer. I am new to streamlit and I do not understand 'The widget will return the username, email, and new random password of the user which should then be transferred to them securely' well. Where I can find the new returned username, email and new random password? In config.yaml file? But the password is hashed, how can I get the new password?
