### ISSUE TITLE
auth with st.set_page_config 

### ISSUE THREAD

**Issue by nfomin99** [mkhorasani/Streamlit-Authenticator#8]
When i define code for authentication in my def main() in wihch st.set_page_config(layout="wide"). My app  not working. 
def main():
   names = ['John Smith','Rebecca Briggs']
   usernames = ['jsmith','rbriggs']
    passwords = ['123','456']
    hashed_passwords = stauth.Hasher(passwords).generate()
    authenticator = stauth.Authenticate(names,usernames,hashed_passwords,
    'some_cookie_name','some_signature_key',cookie_expiry_days=30)
    name, authentication_status, username = authenticator.login('Login','main')
     
    if authentication_status:
        current_plan = data.get_current_capacity_plan()
        setup_multipage(current_plan)
        refresher.start()
    elif authentication_status == False:
        st.error('Username/password is incorrect')
    elif authentication_status == None:
        st.warning('Please enter your username and password')
   
    st.set_page_config(
        page_title='app_name',
        layout='wide',
    ) 
That in error trace  
`StreamlitAPIException: set_page_config() can only be called once per app, and must be called as
the first Streamline command in your script.`

when st.set_page_config is commented out everything works

ideas? i dont understand where st.set_page_config can called. Or how i can define default page config for authentication

**Comment by digitalWestie** [comment]
OK I see.  I ended up putting it in a try / except block
