### ISSUE TITLE
Is there a way to only verify the password?

### ISSUE THREAD

**Issue by Jimchoo91** [mkhorasani/Streamlit-Authenticator#81]
I would like to set this up on my app, but I only want the password to be verified. By this, I mean I want anybody to enter a username (which will not be checked against a pre-existing list), but I want the password they enter to be the correct one in the YAML. Is there a way to do this?

**Comment by mkhorasani** [comment]
Hi @Jimchoo91, no currently there are no provisions to support this functionality. I can look into it for a future iteration though.

**Comment by Jimchoo91** [comment]
Thank you that would be really appreciated.

**Comment by mkhorasani** [comment]
I am currently trying to address this issue, can you please elaborate further on what exactly you mean?

**Comment by mkhorasani** [comment]
Hi @Jimchoo91, I have deemed this feature to be out of the scope of this package and will no longer be continuing its development. Thank you for your understanding.
