### ISSUE TITLE
How to use preauthorization?

### ISSUE THREAD

**Issue by LiminLN** [mkhorasani/Streamlit-Authenticator#86]
How to use preauthorization when set preauthorization=True in authenticator.register_user?

**Comment by mkhorasani** [comment]
Please follow step 5 of the [readme file](https://github.com/mkhorasani/Streamlit-Authenticator). You will also need to populate your [config file](https://github.com/mkhorasani/Streamlit-Authenticator/blob/main/config.yaml) with a list of preauthorized emails of users who can register.

**Comment by LiminLN** [comment]
Got  it. Thanks! @mkhorasani
