### ISSUE TITLE
Azure AAD Oauth2 Support

### ISSUE THREAD

**Issue by cnhsn** [mkhorasani/Streamlit-Authenticator#87]
Hello,

I want to add user authorization system to the application with Azure AD. How can I do that. Does this module have such support? I would appreciate your help.

**Comment by luke-gerschwitz** [comment]
Hi @cnhsn do you have any update on this? Were you able to develop a solution?

Third party IDP support would be amazing.

**Comment by cnhsn** [comment]
Hi @luke-gerschwitz 
I am using oauth2-proxy with Azure AD now. I implemented authn to my NGINX webserver with auth_request module of NGINX. For now, it's working perfect.

**Comment by luke-gerschwitz** [comment]
Thanks @cnhsn it seems like that is the best current solution 😁

**Comment by mkhorasani** [comment]
Please check the latest release. I have implemented OAuth2 using Microsoft and Google handles.
