### ISSUE TITLE
The config.yaml file is not updated on GitHub when registering a new user

### ISSUE THREAD

**Issue by malonvll** [mkhorasani/Streamlit-Authenticator#89]
Hi everyone,

Maybe a stupid question. When running on my local environment, the config.yaml file is automatically updated when registering a new user. But on my online app (files are stored on GitHub), the config.yaml file is not updated automatically, although I get the message that the registration is successful.

Is there a parameter to allow the app to edit the config.yaml file that is in my GitHub files?

**Comment by mkhorasani** [comment]
Hi @malonvll, there is no way for the library to push any changes to a remote GitHub repository. Alternatively, you can save your config.yaml file to disk on the server that you are using or instead write the contents to a database. Please check this [video ](https://www.youtube.com/watch?v=eCbH2nPL9sU)for more information.

**Comment by malonvll** [comment]
@mkhorasani thank you very much for your response, will set-up a database then. And props for your work on this package, it's really helpful!
