### ISSUE TITLE
Invalidate streamlit-authenticator JWT upon logout

### ISSUE THREAD

**Issue by espogian** [mkhorasani/Streamlit-Authenticator#91]
Hi,

I’m using streamlit==1.26.0 and streamlit_authenticator==0.2.3.
I’ve noticed that the JWT which saved upon login (as a cookie, which in the default config is called “random_cookie_name”) retains its validity even if the user logs out.
That is, for instance, if the parameters expiry_days: 1, and within this period of time the user logs out, it is still possible to provide the JWT to the application and retrieve data.
This behaviour is not completely sound under a security perspective, and I’m wondering if there is any mean to:
- Invalidate JWT on user logout or other condition controllable
- Reduce the JWT validity to less than 1 day (e.g. 1 hour)

**Comment by Gungnir762** [comment]
I'm facing the same problem.Have you solved it?

**Comment by Gungnir762** [comment]
it seems that extra_streamlit_components.cookie_manager.delete have some unfix bugs.This func can't delete cookie successfully.
In authenticate.py:
![image](https://github.com/mkhorasani/Streamlit-Authenticator/assets/83220033/7bc2957a-162a-461c-bb3c-c358b2e9c4a4)

**Comment by mkhorasani** [comment]
Please see if this problem still persists with the latest release [v0.3.2](https://github.com/mkhorasani/Streamlit-Authenticator/releases/tag/v0.3.2).
