### ISSUE TITLE
widget after button then not work

### ISSUE THREAD

**Issue by lcg29** [mkhorasani/Streamlit-Authenticator#93]
For example, reset passwords:
````
    if st.button('reset passwords', type="primary"):
        try:
            if authenticator.reset_password(st.session_state["username"], 'Reset password'):
                st.success('reset success ')
        except Exception as e:
            st.error(e)
````
with no work and no 'reset success '

If I delete st.button, it will work
````
        try:
            if authenticator.reset_password(st.session_state["username"], 'Reset password'):
                st.success('reset ')
        except Exception as e:
            st.error(e)
````

**Comment by mkhorasani** [comment]
When you use the reset password widget it will automatically save the new hashed password to the config dictionary you passed to the authenticator object when you first created it. The last step simply ensures that the config dictionary is saved to disk as a config file.

**Comment by thisismygitrepo** [comment]
What if I have a database to update the password instead of config file?
I need that button.

**Comment by MaveriQ** [comment]
@thisismygitrepo did you find a workaround?
