### ISSUE TITLE
Capturing username of failed login attempts

### ISSUE THREAD

**Issue by IndigoJay** [mkhorasani/Streamlit-Authenticator#94]
I would like to write code that blocks a user after 3 failed login attempts. 

Currently, it seems like failed login attempts return the username None.

**Comment by mkhorasani** [comment]
Hi @IndigoJay , this feature has been implemented in release [v0.2.4](https://github.com/mkhorasani/Streamlit-Authenticator/releases/tag/v0.2.4). You can retrieve the number of failed login attempts a user has made by accessing st.session_state['failed_login_attempts'] which returns a dictionary with the username as key and the number of failed attempts as the value.
