### ISSUE TITLE
Login needs 2x click (authentication_status possible error)

### ISSUE THREAD

**Issue by yash2mehta** [mkhorasani/Streamlit-Authenticator#95]
Hi, I think the authentication_status is not benig able to persist across multiple pages. Please see this page for more information (source code + issues):

https://discuss.streamlit.io/t/login-button-random-behavior/54909

@mkhorasani can you please help, would be greatly appreciated

**Comment by mkhorasani** [comment]
Hi, @yash2mehta sure will take a look and hopefully fix any issues in the next release. Thanks.

**Comment by mkhorasani** [comment]
Dear @yash2mehta, if you are using Streamlit-Authenticator with multi-page apps, you will have to recreate the authenticator object on **each and every page** and invoke the login method as shown below:

```
authenticator = stauth.Authenticate(
    config['credentials'],
    config['cookie']['name'],
    config['cookie']['key'],
    config['cookie']['expiry_days'],
    config['pre-authorized']
)

authenticator.login()
```

This is to ensure that when a user hard refreshes the page and the session state variables related to re-authentication are lost, the authenticator object is there to re-initialize them from the cookie saved on the browser. Please let me know if this solves your issues and I will close this issue.
